K gubin/revit room viewer
Bim4Everyone/RevitPlugins pull request #104
Opened 2024-10-24 07:39 UTC by KGubin

Создал плагин RevitRoomViewer
https://jira.a101.ru/browse/BIMCOMMON-167

2024-10-25 08:05 UTC, dosymep requested changes

2024-10-25 08:05 UTC, dosymep commented on src/RevitRoomViewer/ViewModels/MainViewModel.cs
> +            RevitVersion = "Revit 2023";
это значит, что этот код будет во всех версиях ниже 2023 и включая ее, а судя по значению переменной там ожидается только для 2023 версии

2024-10-25 08:05 UTC, dosymep commented on src/RevitRoomViewer/Views/MainWindow.xaml
> +          ItemsSource="{Binding AllRooms}"
вообще по хорошему нужно биндится к классам, которые реализуют `INotifyPropertyChanged`, в `AllRooms` у тебя обычный класс

2024-10-25 08:05 UTC, dosymep commented on src/RevitRoomViewer/ViewModels/MainViewModel.cs
> +            AcceptViewCommand = RelayCommand.Create(AcceptView);
нужно добавить любой вариант валидации, что свойство какое-то не заполнено и тп, сделай в том же виде, который у нас в платформе обычно пишется

2024-10-25 08:05 UTC, dosymep commented on src/RevitRoomViewer/ViewModels/MainViewModel.cs
> +                if(RoomsWithSettings.ContainsKey(room.RoomName)) {
для ключей элементов рекомендую использовать их идентификаторы

2024-10-25 08:05 UTC, dosymep commented on src/RevitRoomViewer/ViewModels/MainViewModel.cs
> +        }
данный код можно упростить

2024-10-25 08:06 UTC, dosymep commented
забыл написать, если не используешь локализацию ее лучше всю удалить, либо, если используешь удаляй неиспользуемые языки

2024-10-28 14:23 UTC, KGubin commented on src/RevitPlugins/Models/PluginConfig.cs
Хорошо

2024-10-28 14:23 UTC, KGubin commented on src/RevitRoomViewer/Views/MainWindow.xaml
> +          ItemsSource="{Binding AllRooms}"
Понял

2024-10-28 14:24 UTC, KGubin commented on src/RevitRoomViewer/ViewModels/MainViewModel.cs
> +            AcceptViewCommand = RelayCommand.Create(AcceptView);
Добавил

2024-10-28 14:24 UTC, KGubin commented on src/RevitRoomViewer/ViewModels/MainViewModel.cs
> +                if(RoomsWithSettings.ContainsKey(room.RoomName)) {
Хорошо

2024-10-29 13:54 UTC, vlastroG requested changes
Скорректируй стиль кода под наш: https://github.com/Bim4Everyone/RevitPlugins/blob/master/CODE_STYLE_GUIDE.md

Скорректируй архитектуру плагина: вместо сохранения словаря помещений сохраняй коллекцию уровней с помещениями. Для каждой модели (обертки над ревитовскими Room и Level) у тебя будет модель представления (ViewModel) для отображения в GUI

2024-10-29 13:54 UTC, vlastroG commented on src/RevitPlugins/Models/PluginConfig.cs
надо откатить изменения этого файла до мастер ветки. исползуй команду:
`git reset <commit hash> <filename>`

2024-10-29 13:54 UTC, vlastroG commented on src/RevitRoomViewer/Models/PluginConfig.cs
> +        public Dictionary<string, RoomElement> RoomsWithSettings { get; set; }
Ключом словаря можно сделать `ElementId` вместо строки. Класс `ConfigSerializer`, который здесь добавляется в 17 строке внутри себя содержит логику по сериализации и десереализации `ElementId`. Поэтому `ElementId` можно использовать во всех конфигах для плагинов.

Но исходя из твоего плагина для просмотра помещений по уровням, здесь лучше сохранять не словарь, а `LevelElement[]`, в каждом из которых будет `RoomElement[]`. В GUI потом соответственно будет отображаться `ObservableCollection<LevelElementViewModel>`, где в каждом `LevelElementViewModel` будут `ObservableCollection<RoomElementViewModel>`.

2024-10-29 13:54 UTC, vlastroG commented on src/RevitRoomViewer/Models/RevitRepository.cs
> +        }
разнеси этот метод на несколько разных: для получения помещений, для получения уровней.

С помещениями в ревите куча тонкостей:
1. Лучше использовать `RoomFilter` https://www.revitapidocs.com/2022/356881b1-5ee4-621a-0379-965c3e6f6dcf.htm
2. Лучше проверять на площадь, если тебе нужны "нормальные" помещения.
Пример:
```
Room[] rooms = new FilteredElementCollector(Document, Document.ActiveView.Id)
    .WherePasses(new RoomFilter())
    .Cast<Room>()
    .Where(r => r.Area > 0)
    .ToArray();
```

2024-10-29 13:54 UTC, vlastroG commented on src/RevitRoomViewer/Models/RevitRepository.cs
> +                        return roomElement;
вместо лямбда выражения сделай отдельный метод

2024-10-29 13:54 UTC, vlastroG commented on src/RevitRoomViewer/Models/RoomElement.cs
> +        public string LevelId => _room.LevelId.ToString();
для Id исполбзуй тип `ElementId` вместо строк

2024-10-29 13:54 UTC, vlastroG commented on src/RevitRoomViewer/ViewModels/LevelViewModel.cs
> +        public List<RoomElement> Rooms { get => _rooms; }
вместо `List` в классах, наследуемых от `BaseViewModel`, лучше использовать `ObservableCollection`

2024-10-29 13:54 UTC, vlastroG commented on src/RevitRoomViewer/Views/MainWindow.xaml
> +                                        Binding="{Binding  Description}" />
добавь `UpdateSourceTrigger=PropertyChanged`

2024-10-29 13:54 UTC, vlastroG commented on src/RevitRoomViewer/Views/MainWindow.xaml
отсортируй свойства в контролах: простые типы сверху, сложные снизу. И все свойства на отдельной строке на 4 пробела правее названия контрола. Например:
*вместо:*
```
<DataGridTextColumn Header="Имя"
    Binding="{Binding Name}" 
    IsReadOnly="True" />
```    
*пиши так:*
```
<DataGridTextColumn
    Header="Имя"
    IsReadOnly="True"
    Binding="{Binding Name}" />
```    

Это автоформатирование можно включить в Visual Studio:
![image](https://github.com/user-attachments/assets/10d5ea0f-f336-4ef9-b886-8157b0790091)

2024-10-29 13:54 UTC, vlastroG commented on src/RevitRoomViewer/ViewModels/MainViewModel.cs
> +                RoomsWithSettings = setting.RoomsWithSettings;
Используй фигурные скобки, даже если они не обязательны.
А выражение можно упростить следующим образом:
```
RoomsWithSettings = setting?.RoomsWithSettings ?? new Dictionary<string, RoomElement>();
```

2024-10-29 13:54 UTC, vlastroG commented on src/RevitRoomViewer/ViewModels/MainViewModel.cs
> +                RoomsWithSettings = setting.RoomsWithSettings;
Используй фигурные скобки, даже если они не обязательны.
Упрости выражение:
```
RoomsWithSettings = setting?.RoomsWithSettings ?? new Dictionary<string, RoomElement>();
```

2024-10-29 13:54 UTC, vlastroG commented on src/RevitRoomViewer/Views/MainWindow.xaml
> +                                        Binding="{Binding  Description}" />
добавь `UpdateSourceTrigger=PropertyChanged`

2024-10-29 13:54 UTC, vlastroG commented on src/RevitRoomViewer/Views/MainWindow.xaml
сделай каждое свойство контрола на отельной строке, отступ от названия контрола на 4 пробела вправо. Сортировка свойств по типу: простые типы сверху, сложные снизу. Пример:
*вместо*:
```
                    <DataGrid ItemsSource="{Binding Rooms}"
                              AutoGenerateColumns="False"
                              SelectionMode="Single"
                              HorizontalAlignment="Stretch"
                              VerticalAlignment="Stretch">
```
*пиши так*
```
                    <DataGrid
                        AutoGenerateColumns="False"
                        SelectionMode="Single"
                        HorizontalAlignment="Stretch"
                        VerticalAlignment="Stretch"
                        ItemsSource="{Binding Rooms}">
```

Это форматирование можно настроить в студии:
![image](https://github.com/user-attachments/assets/a20ce44e-da73-48f1-b249-9543836651f7)

2024-10-29 13:54 UTC, vlastroG commented on src/RevitRoomViewer/ViewModels/MainViewModel.cs
> +                                    ?? _pluginConfig.AddSettings(_revitRepository.Document);
отступ многострочных выражений 4 пробела
вместо:
```
            RevitSettings setting = _pluginConfig.GetSettings(_revitRepository.Document)
                                    ?? _pluginConfig.AddSettings(_revitRepository.Document);
```
так:
```
            RevitSettings setting = _pluginConfig.GetSettings(_revitRepository.Document)
                ?? _pluginConfig.AddSettings(_revitRepository.Document);
```

2024-10-31 07:32 UTC, vlastroG requested changes
То, что забыл в прошлый раз по стилю:
Сортировку членов классов сделай по https://github.com/Bim4Everyone/RevitPlugins/blob/master/CODE_STYLE_GUIDE.md
И не используй публичные изменяемые поля, вместо них юзай свойства. Публичные поля могут быть только `const`.

Плагины стараемся делать, используя паттерн MVVM. То есть у нас есть слой Model, в котором у тебя сейчас RevitRespository, PluginConfig, RoomElement. Слой ViewModel, в котором LevelViewModel, MainViewModel. И слой View в котором MainWindow.

Классы из Model внутри себя никак не используют классы из ViewModel и из View. Классы из ViewModel используют классы из Model. Классы из View используют классы из ViewModel.

Тип `ObservableCollection` (https://learn.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.observablecollection-1?view=net-8.0) нам нужен только для того, чтобы привязывать коллекции из ViewModel к View, потому что `ObservableCollection : INotifyPropertyChanged, INotifyCollectionChanged`. Короче говоря `ObservableCollection` должен использваться только в классах из ViewModel и View. Внутри классов из Model мы не используем `ObservableCollection`, а используем коллекции из `System.Collections.Generic` : https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic?view=netframework-4.8 , например:
- ICollection
- IEnumerable
- IList
- IReadOnlyCollection (но реализация `ReadOnlyCollection` в `System.Collections.ObjectModel`)
- Array
- List
- HashSet

### Резюме:
- доправь стиль кода -сортировку членов классов
- убери использование типа ObservableCollection из классов PluginConfig и RevitRepository
- внеси остальные мелкие исправления

2024-10-31 07:32 UTC, vlastroG commented on src/RevitRoomViewer/Models/RevitRepository.cs
> +            Room[] rooms = new FilteredElementCollector(Document, Document.ActiveView.Id)
Не заметил, когда в прошлый раз тебе пример кидал для получения помещений. У `FilteredElementCollector` сейчас есть 3 конструктора: https://www.revitapidocs.com/2022/a9599101-043e-ddbc-f50a-8e55cd615daf.htm . Тот, который ты тут используешь (который в моем примере был) , получает элементы, видимые  только на активном виде.

2024-10-31 07:32 UTC, vlastroG commented on src/RevitRoomViewer/RevitRoomViewerCommand.cs
> +            PluginName = "RevitRoomViewer";
Пропиши название плагина на русском языке

2024-10-31 07:32 UTC, vlastroG commented on src/RevitRoomViewer/RevitRoomViewerCommand.cs
> +                        c => c.Kernel.Get<ILocalizationService>());
Удали локализацию

2024-10-31 07:32 UTC, vlastroG commented on src/RevitRoomViewer/RevitRoomViewerCommand.cs
> +                        c => c.Kernel.Get<MainViewModel>())
Добавь настройку свойства `Window.Title` и привяжи его к `PluginName` свойству

2024-10-31 07:32 UTC, vlastroG commented on src/RevitRoomViewer/ViewModels/MainViewModel.cs
> +        public ObservableCollection<RoomElement> RoomsWithSettings;
Вместо публичных полей используй свойства. Публичные поля могут быть только `const`

2024-10-31 07:32 UTC, vlastroG commented on src/RevitRoomViewer/Views/MainWindow.xaml
> +    Title="{DynamicResource MainWindow.Title}"
Убери здесь привязку `Title`, сделай ее в инициализации контейнера в `RevitRoomViewerCommand.Execute`

2024-10-31 07:32 UTC, vlastroG commented on src/RevitRoomViewer/Views/MainWindow.xaml
> +                IsCancel="True" />
У этих кнопок у нас такой принцип:
- ОК (Сохранить): сохраняет изменения в окне и закрывает окно с `DialogResult = true`. На Enter автоматом жмется.
- Отмена: не сохраняет изменения и закрывает окно с `DialogResult = false`. На Esc автоматом жмется.

`DialogResult` потом подватывается методом `BasePluginCommand.Notification` и в правом нижнем углу экрана появляется уведомление об успешном/не успешном/отмененном выполнении плагина

Поэтому добавь у себя на Сохранить:
- закрытие окна с `DialogResult = true`
- указание свойства `IsDefault`
на Отменить:
- закрытие окна с `DialogResult = false`

2024-10-31 11:35 UTC, vlastroG requested changes

2024-10-31 11:35 UTC, vlastroG commented on src/RevitRoomViewer/Views/MainWindow.xaml
> +                Command="{Binding AcceptViewCommand}" />
Добавь назначение свойства `IsDefault`

2024-10-31 11:35 UTC, vlastroG commented on src/RevitRoomViewer/ViewModels/LevelViewModel.cs
Скорректируй сортировку членов класса

2024-10-31 11:35 UTC, vlastroG commented on src/RevitRoomViewer/Models/RevitRepository.cs
> +        public ObservableCollection<LevelViewModel> GetLevels(List<RoomElement> roomsSettings = null) {
Убери использование `LevelViewModel` и `ObservableCollection` из `RevitRepository`

2024-10-31 12:15 UTC, vlastroG requested changes

2024-10-31 12:15 UTC, vlastroG commented on src/RevitRoomViewer/Models/RevitRepository.cs
> +        public List<LevelViewModel> GetLevels(List<RoomElement> roomsSettings = null) {
`LevelViewModel` тоже надо убрать из `RevitRepository`

2024-10-31 12:15 UTC, vlastroG commented on src/RevitRoomViewer/ViewModels/MainViewModel.cs
`RoomsWithSettings` свойства сейчас нет здесь, поэтому не компилируется

2024-10-31 14:51 UTC, vlastroG approved these changes

2024-10-31 15:04 UTC, closed without merging