RevitMirroredElements: Создание плагина
Bim4Everyone/RevitPlugins pull request #120
Opened 2024-11-18 13:20 UTC by KGubin

Создание плагина, реализация следующего функционала:
- Добавление признака "ФОП_зеркальность" в Revit.
- Проставление признака "ФОП_зеркальность" у элементов.
- Фильтрация элементов с признаком "ФОП_зеркальность" = 1, на временном виде.
- Выделение элементов с признаком "ФОП_зеркальность" = 1, на активном виде.

2024-11-20 13:14 UTC, vlastroG requested changes
## Общий функционал:

  - Добавить валидацию на тип активного документа (семейство/проект), добавить валидацию на тип активного вида
  - Проверить создание фильтра для временного вида. Как будто не обновляется категория.
  - Добавить сохранение выбранных настроек в окне.
  - не очень понятно, зачем выделять все элементы (когда выключена галочка для временного вида). Может лучше выделять толко элементы с ФОП_Зеркальность=1 ?

## GUI:

### Главное окно:

  - Сделать кнопки ОК и Отмена, чтоб было как в других плагинах. Добавить также отмену на esc, а ОК на enter.
  - Размеры окна можно сделать не изменяемыми.
  - Скорректировать сообщение валидации в окне. При не заданных категориях сообщение "Необходимо выбрать элементы".
  - Сделать отключение кнопок "Выбрать" в соответствии с включенными радиокнопками.
  - При выборе элементов сделать выбор элементов только тех категорий, у которых есть параметр ФОП_Зеркальность. Также фильтровать выбранные перед запуском плагина элементы на наличие этого параметра.

### Окно выбора категории:

  - Выводить в список категорий только те категории, в которые добавлен параметр ФОП_Зеркальность
  - отключить возможность редактирования названия категории
  - отключить возможность удалять категорию из списка
  - сделать, чтобы можно было скроллить
  - сделать, чтобы при растягивании окна список категорий растягивался по вертикали вместе с окном
  - Вместо кнопки "Выполнить" сделать кнопки ОК и Отмена. Добавить также отмену на esc

2024-11-20 13:14 UTC, vlastroG commented on src/RevitMirroredElements/ViewModels/CategoriesViewModel.cs
> +                .ToList());
new List не нужно писать, ToList уже возвращает список

2024-11-20 13:14 UTC, vlastroG commented on src/RevitMirroredElements/RevitMirroredElementsCommand.cs
> +                mainWindow.Title = PluginName;
сделай настройку этих свойств через ninject

2024-11-20 13:14 UTC, vlastroG commented on src/RevitMirroredElements/Models/RevitRepository.cs
Между методами сделай отступ в 1 строку. Внутри методов пустых строк для отступов как будто можно меньше :)
Публичные константы напиши перед конструктором.
Большие методы лучше разнеси на несколько маленьких.

2024-11-20 13:14 UTC, vlastroG commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +        }
здесь лучше вернуть ElementId.InvalidElementId , если null

2024-11-20 13:25 UTC, KGubin commented on src/RevitMirroredElements/README.md
> +
Написал

2024-11-25 10:38 UTC, dosymep requested changes

2024-11-25 10:38 UTC, dosymep commented on src/RevitMirroredElements/Models/PluginConfig.cs
> +        public bool EnableFilter { get; set; }
ты можешь просто enum сохранить, зачем такие сложности?

2024-11-25 10:38 UTC, dosymep commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +                .FirstOrDefault(p => p.Name == "<Solid>");
возможно не будет работать на других локализациях

2024-11-25 10:38 UTC, dosymep commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +            view.EnableTemporaryViewPropertiesMode(view.Id);
в этот метод надо передать шаблон вида (попробуй использовать тот же самый из переданного view)

2024-11-25 10:38 UTC, dosymep commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +            var paramId = GetParameterIdByName(SharedParamsConfig.Instance.ElementMirroring.Name);
в платформе есть метод получения ParameterElement

2024-11-25 10:38 UTC, dosymep commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +            if(paramId == ElementId.InvalidElementId) {
в платформе есть метод проверки ElementId на null

2024-11-25 10:38 UTC, dosymep commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +            var newCategoryIds = elements
рекомендую список категорий получить с параметра зеркальности (но это лучше уточнить)

2024-11-25 10:38 UTC, dosymep commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +            return selectedCategories
есть [MultiCategoryFilter](https://www.revitapidocs.com/2024/34f8d848-4440-e880-3277-4f90e5cf3072.htm)

2024-11-25 10:38 UTC, dosymep commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +        .Where(item => item.OwnerViewId == viewId)
не очень уверен, что это так делается, так как у [FilteredElementCollector](https://www.revitapidocs.com/2024/6359776d-915e-f8a2-4147-b31024671ee1.htm) есть перегрузка конструктора

2024-11-25 10:38 UTC, dosymep commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +        public ICollection<Element> GetElements(ICollection<ElementId> elementIds) {
рекомендую работать с элементами, чтобы не делать 100500 конвертаций из идентификаторы в элементы

2024-11-25 10:38 UTC, dosymep commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +            var sharedParamElement = new FilteredElementCollector(Document)
В платформе есть метод получения биндингов

2024-11-25 10:38 UTC, dosymep commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +        public ICollection<Category> GetCategoriesByElementIds(ICollection<ElementId> elementIds) {
категории лучше получать из параметра

2024-11-25 10:38 UTC, dosymep commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +                var isMirrored = element.GetParamValue<double>(SharedParamsConfig.Instance.ElementMirroring.Name);
получать параметры надо из платформы, `GetParamValue<double>(SharedParamsConfig.Instance.ElementMirroring)`

2024-11-25 10:38 UTC, dosymep commented on src/RevitMirroredElements/ViewModels/MainViewModel.cs
> +        }
можно использовать enum

2024-11-25 10:38 UTC, dosymep commented on src/RevitMirroredElements/ViewModels/MainViewModel.cs
> +        private bool IsElementMirrored(Element element) {
если твой код работает только с FamilyInstance работай только с ним, зачем тебе 100500 конвертаций одного в другое?

2024-11-27 07:25 UTC, dosymep requested changes

2024-11-27 07:25 UTC, dosymep commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +            view.EnableTemporaryViewPropertiesMode(view.Id);
> Если передаю TepmplateViewId то не работает, не включается временный вид

тогда стоит написать почему такое решение было сделано в комментариях

2024-11-27 07:25 UTC, dosymep commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +            if(!param.Id.IsNotNull()) {
в платформе есть проверка на null

2024-11-27 07:25 UTC, dosymep commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +            var param = Document.GetSharedParam(SharedParamsConfig.Instance.ElementMirroring.Name);
в платформе есть метод получения ParatemerElement по RevitParam

2024-11-27 07:25 UTC, dosymep commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +            var sharedParamElement = Document.GetSharedParam(SharedParamsConfig.Instance.ElementMirroring.Name);
рекомендую использовать метод из RevitParam

2024-11-27 07:25 UTC, dosymep commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +            var categories = Document
у RevitParam есть метод получения биндинга

2024-11-27 07:25 UTC, dosymep commented on src/RevitMirroredElements/Models/RevitRepository.cs
> +        public List<Category> GetSaveCategories(List<ElementId> elementsIds) {
очень странный метод, либо он не работает, либо название параметра не то

2024-11-27 07:25 UTC, dosymep commented on src/RevitMirroredElements/RevitMirroredElementsCommand.cs
> +                    TaskDialog.Show("Ошибка", "Плагин может быть запущен только в следующих типах видов:\n- 3D Вид\n- План этажа\n- Разрез\n- Фасад.");
а это требование было оговорено?

2024-11-27 07:53 UTC, KGubin commented on src/RevitMirroredElements/RevitMirroredElementsCommand.cs
> +                    TaskDialog.Show("Ошибка", "Плагин может быть запущен только в следующих типах видов:\n- 3D Вид\n- План этажа\n- Разрез\n- Фасад.");
Да обговорил

2024-11-27 10:42 UTC, dosymep approved these changes

2024-11-27 10:43 UTC, merged