RevitRemoveRoomTags: реализован проект удаления марок помещений
Bim4Everyone/RevitPlugins pull request #13
Opened 2023-11-17 14:54 UTC by DivinN

2023-11-20 06:15 UTC, dosymep requested changes

2023-11-20 06:27 UTC, dosymep requested changes

2023-11-20 06:27 UTC, dosymep commented on RevitRemoveRoomTags/README.md
> +nuke compile --plugin-name RevitRemoveRoomTags
обнови команду сборки и публикации

2023-11-29 11:23 UTC, DivinN commented on RevitRemoveRoomTags/README.md
> +Описание проекта
Добавил

2023-11-29 11:23 UTC, DivinN commented on RevitRemoveRoomTags/RevitRemoveRoomTagsCommand.cs
> +                if(window.ShowDialog() == true) {
Заменил

2023-11-29 11:24 UTC, DivinN commented on RevitRemoveRoomTags/ViewModels/MainViewModel.cs
> +            LoadConfig();
Добавил параметр для сохранения

2023-12-01 12:31 UTC, dosymep submitted a review, later dismissed

2023-12-14 09:04 UTC, vlastroG requested changes

2023-12-14 09:04 UTC, vlastroG commented on RevitRemoveRoomTags/ViewModels/MainViewModel.cs
> +                List<ElementId> tagsForDel = new List<ElementId>();
Если тебе нужны в tagsForDel только различающиеся элементы, то лучше использовать HashSet:
`HashSet<ElementId> tagsForDel = new HashSet<ElementId>();`

И тогда удаление будет так:
```
if(tagsForDel.Count > 0) {
    _revitRepository.Document.Delete(tagsForDel);
}
```

2023-12-14 12:04 UTC, vlastroG approved these changes

2023-12-14 12:42 UTC, vlastroG approved these changes

2023-12-14 13:00 UTC, merged