Redomine/revit3d view schemas
Bim4Everyone/RevitPlugins pull request #15
Opened 2023-11-21 14:45 UTC by Redomine

Плагин копирует активный 3D-вид с применением на него фильтра, который создает или по имени системы, или по ФОП_ВИС_Имени системы, для дальнейшего оформления инженерами

2023-11-22 08:47 UTC, dosymep requested changes

2023-11-22 08:47 UTC, dosymep commented on .nuke/parameters.Revit3DvikSchemas.json
> +  "PluginName": "Revit3DvikSchemas",
У тебя в названии скрипта ошибка название плагина "Revit3dViewSchemas", а у тебя "Revit3DvikSchemas", надо переименовать проект, и переименовать этот файл и изменить везде это название на новое

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/Models/HvacSystem.cs
> +                _isChecked = value;
У BaseViewModel есть метод RaisePropertyChanged

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/Models/PluginConfig.cs
> +using dosymep.Bim4Everyone;
Рекомендую весь выбор пользователя сохранять в конфигурации, если же конфиг не нужен, то его надо удалить

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/Models/RevitRepository.cs
> +using System.Collections.Generic;
У тебя сломалась кодировка файла, посоветуйся как справить с ssenya

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +    internal class UniqName {
Сделай поля свойствами и назови с большой буквы

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +        private bool combineViews;
Приватные поля должныначинаться с нижнего подчеркивания "_combineViews"

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +        public List<ElementFilter> CreateElementFilter(List<string> systemNameList) {
Раздели метод на несколько простых, получение идентификатора параметра и на создание фильтра

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +            List<BuiltInCategory> allCategories = new List<BuiltInCategory>() { BuiltInCategory.OST_DuctFitting,
Сразу создай список идентификаторов категорий

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +            List<BuiltInCategory> allCategories = new List<BuiltInCategory>() { BuiltInCategory.OST_DuctFitting,
каждую категорию надо писать на новой строке

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +            Transaction t = _revitRepository.Document.StartTransaction("Создать схемы");
для транзакций используй конструкцию [using](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/using)

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +            RevitRepository revitRepository = _revitRepository;
зачем тут переприсвоение?

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +        public void CreateSelectedCommand(ObservableCollection<HvacSystemViewModel> list, bool _useFopNames, bool _combineViews) {
Передаваемые параметры в метод должны быть без нижнего подчеркивания, а поля класса начинаться с нижнего подчеркивания

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +        private void CopyViewCreateFilters(List<HvacSystemViewModel> systems) {
упрости метод разделив его на более простые методы

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +        private static UniqName WasMet(List<Element> elements, UniqName uniqName) {
не ясно что делает метод, улучши нейминг

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +        private static string IsNameUniqOrMakeNew(string name, List<Element> elements) {
когда нибудь у тебя этот код зависнет

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +        private static string IsNameUniqOrMakeNew(string name, List<Element> elements) {
не ясно что в итогде должен сделать код

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/README.md
> +Описание проекта
не написал описание проекта, так же его добавь в основной README.md

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/Revit3DvikSchemasCommand.cs
> +using System.Windows;
У файла сломана кодировка, нужно ее обновить

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/ViewModels/MainViewModel.cs
> +            ComboBoxVars = new ObservableCollection<String>() { "Имя системы", "ФОП_ВИС_Имя системы" };
делай нейминг более логичным

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/ViewModels/MainViewModel.cs
> +            bool RevitUseFopNames = UseFopNames;
переменные методы должны называться с маленькой буквы

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/ViewModels/MainViewModel.cs
> +            if(!(_revitRepository.Document.ActiveView.ViewType == ViewType.ThreeD)) {
такие вещи лучше проверять до открытия основного окна плагина

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/ViewModels/MainViewModel.cs
> +            if(!_revitRepository.Document.IsExistsSharedParam("ФОП_ВИС_Имя системы")) {
такие проверки лучше вывести до запуска главного окна

2023-11-22 08:47 UTC, dosymep commented on Revit3DvikSchemas/Views/MainWindow.xaml.cs
> +        private void ListView_SelectionChanged(object sender, System.Windows.Controls.SelectionChangedEventArgs e) {
не используемый хендлер события

2023-12-04 06:52 UTC, Redomine commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +        private bool combineViews;
Переименовал

2023-12-04 07:57 UTC, Redomine commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +            List<BuiltInCategory> allCategories = new List<BuiltInCategory>() { BuiltInCategory.OST_DuctFitting,
Переписал

2023-12-04 08:00 UTC, Redomine commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +            RevitRepository revitRepository = _revitRepository;
Осталось от старых вариантов, затер

2023-12-04 08:13 UTC, Redomine commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +        public void CreateSelectedCommand(ObservableCollection<HvacSystemViewModel> list, bool _useFopNames, bool _combineViews) {
Поправил

2023-12-04 09:18 UTC, Redomine commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +        private void CopyViewCreateFilters(List<HvacSystemViewModel> systems) {
Выделил повторения в метод CopyView

2023-12-04 10:06 UTC, Redomine commented on Revit3DvikSchemas/ViewModels/MainViewModel.cs
> +            if(!(_revitRepository.Document.ActiveView.ViewType == ViewType.ThreeD)) {
Я немного не по своему замыслу тут сделал. Эта ошибка должна вываливаться только при галочке "Схемы по ФОП_ВИС_Имя системы", в остальных случаях работа продолжается

2023-12-04 10:06 UTC, Redomine commented on Revit3DvikSchemas/ViewModels/MainViewModel.cs
> +            if(!_revitRepository.Document.IsExistsSharedParam("ФОП_ВИС_Имя системы")) {
Я немного не по своему замыслу тут сделал. Эта ошибка должна вываливаться только при галочке "Схемы по ФОП_ВИС_Имя системы", в остальных случаях работа продолжается

2023-12-04 14:12 UTC, Redomine commented on Revit3DvikSchemas/Models/RevitRepository.cs
> +using System.Collections.Generic;
Заменил кодировку на UTF-8

2023-12-05 06:50 UTC, Redomine commented on Revit3DvikSchemas/Models/ViewMaker.cs
> +        private static UniqName WasMet(List<Element> elements, UniqName uniqName) {
Удалил его с концами, не нужен

2023-12-05 07:06 UTC, Redomine commented on .nuke/parameters.Revit3DvikSchemas.json
> +  "PluginName": "Revit3DvikSchemas",
Переименовал сам пуллреквест, имя плагина в порядке

2024-08-28 07:23 UTC, closed without merging