RevitServerFolders: Полностью переделан плагин
Bim4Everyone/RevitPlugins pull request #19
Opened 2023-12-12 11:28 UTC by dosymep

Был полностью переработана плагин.

- был переработан интерфейс плагина
- был удален плагин экспорта вида Navisworks из плагина экспорта RVT файлов из RS
- был добавлен экспорт площадок в Navisworks
- была добавлена возможность выключать экспортируемые файлы
- убрана не работающая настройка экспорта вместе со связанными файлами

Экспорт файлов RVT из RS
![Экспорт файлов RVT из RS](https://github.com/Bim4Everyone/RevitPlugins/assets/5417225/13ba65f9-635e-4e5b-9de1-6070591c77cc)

Экспорт вида Navisworks
![Экспорт вида Navisworks](https://github.com/Bim4Everyone/RevitPlugins/assets/5417225/754a491e-8602-4699-9b56-4dab3e767876)

2023-12-13 08:09 UTC, vlastroG requested changes

2023-12-13 08:09 UTC, vlastroG commented on RevitServerFolders/ViewModels/Rs/MainViewModel.cs
> +            if(args.Row is RsModelObjectViewModel rsModelObject) {
Можно сразу написать
            return args.Row is RsModelObjectViewModel rsModelObject
                && rsModelObject.LoadChildrenCommand.CanExecute(default);

2023-12-13 08:09 UTC, vlastroG commented on RevitServerFolders/ViewModels/Rs/RsModelObjectViewModel.cs
Методы лучше написать в порядке:
public
protected
private

2023-12-13 08:09 UTC, vlastroG commented on RevitServerFolders/Views/MainWindow.xaml
> +    Height="450" Width="800"
Можно указать также свойства MinHeight и MinWidth, чтобы нельзя было сделать окно слишком маленьким

2023-12-13 08:09 UTC, vlastroG commented on RevitServerFolders/Views/MainWindow.xaml
> +        <StackPanel
Вместо горизонтальных StaclPanel можно использовать DockPanel

2023-12-13 09:48 UTC, dosymep commented on RevitServerFolders/Models/ModelObject.cs
я не думаю, что требуется явно создавать конструктор по умолчанию, потому что по сути он будет пустым. Другое дело, если бы у класса была какая-то своя инициализация полей.

2023-12-14 06:02 UTC, vlastroG approved these changes

2023-12-14 06:03 UTC, merged