RevitWallsFinishing: Добавлен плагин по отделке стен
Bim4Everyone/RevitPlugins pull request #28
Opened 2024-01-23 12:57 UTC by vlastroG

# Плагин создает стены по контуру заданных помещений из активного документа.

В настройках задается:

- режим выбора стен
- тип создаваемых стен
- отметка верха стены от уровня
- смещение низа стены от уровня

![image](https://github.com/Bim4Everyone/RevitPlugins/assets/87359016/c7b11563-f707-4143-8260-032a04618ff4)

Созданные стены имеют линию привязки "Чистовая поверхность: Внутренняя" и отключенную галочку "Граница помещения". Также отделочные стены соединяются с элементами из активного документа (стенами, колоннами, несущими колоннами), которые образуют границу помещения. Соединение (выделено желтым) будет выполнено даже если эти элементы перекрыты линией разделителя помещений (выделено красным):

![image](https://github.com/Bim4Everyone/RevitPlugins/assets/87359016/b1fcfcfb-adf0-4bde-bbf4-04c619798a8d)

2024-05-27 07:39 UTC, dosymep requested changes

2024-05-27 07:39 UTC, dosymep commented on src/RevitFinishingWalls/Services/Selection/SelectionFilterRooms.cs
У тебя тут разные типы проверок между AllowElement и AllowReference. 
Вообще при выделении помещений AllowReference нужен (может ему лучше false всегда возвращать)?

2024-05-27 07:39 UTC, dosymep commented on src/RevitFinishingWalls/Services/Creation/Implements/RoomFinisher.cs
> +            using(var transaction = _revitRepository.Document.StartTransaction("BIM: Создание отделочных стен")) {
Метод из платформы, который стартует транзакцию сам автоматически вставляет текст `BIM:`.

2024-05-27 07:39 UTC, dosymep commented on src/RevitFinishingWalls/ViewModels/MainViewModel.cs
> +                _messageBoxService.Show(error, "BIM", MessageBoxButton.OK, MessageBoxImage.Warning, MessageBoxResult.OK);
Список ошибок лучше вывести в отдельном окне, а не в месседж боксе

2024-05-27 07:39 UTC, dosymep commented on src/RevitFinishingWalls/Resources/Converters/EnumDescriptionTypeConverter.cs
У нас в платформе есть данный конвертер
![image](https://github.com/Bim4Everyone/RevitPlugins/assets/5417225/595c2d38-c363-48e0-94b2-925fe03edc30)

2024-05-27 07:39 UTC, dosymep commented on src/RevitFinishingWalls/ViewModels/MainViewModel.cs
> +                            if(offset < -5000) {
Откуда числа -5000 и 5000? Создай переменную и добавь в документацию об этом ограничении.

2024-05-27 07:39 UTC, dosymep commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +            switch(roomGetterMode) {
Я бы создал три отдельных класса по получению элементов

2024-05-27 07:39 UTC, dosymep commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +            var views3D = new FilteredElementCollector(Document)
Добавь фильтрацию шаблонов, возможна ситуация, когда пользователь создаст шаблон с именем `3D`.

2024-05-27 07:39 UTC, dosymep commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +            const string defaultView3dName = "3D";
Рекомендую название вида изменить, так же добавить это название в документацию.

2024-05-27 07:39 UTC, dosymep commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +            } else if(borderEl != null) {
Выражение всегда истинно.

2024-05-27 07:39 UTC, dosymep commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +                return Array.Empty<Element>();
Недостижимый код.

2024-05-27 07:39 UTC, dosymep commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +                return new XYZ[] { curve.Evaluate(0.5, true) };
Почему `0.5`, надо бы написать в комментарии.

2024-05-27 07:39 UTC, dosymep commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +                return new XYZ[] { curve.Evaluate(0.5, true) };
Все, разобрался, идет вычисление по нормализованной линии, а нормализованная линия всегда равна единице. (это может стоит добавить)

2024-05-27 07:39 UTC, dosymep commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +            } else {
Else можно убрать :)

2024-05-27 07:39 UTC, dosymep commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +        private Curve CombineCurves(Curve curveFirst, Curve curveSecond) {
А ты уверен, что линии всегда прямые? если да, то надо написать почему в комментарий, и не забыть добавить в документацию.

2024-05-27 07:39 UTC, dosymep commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +        private bool IsContinuation(Curve first, Curve second) {
Отрезок может быть кривым и продолжать другой отрезок. Надо написать почему у нас линии всегда прямые в комментарий, и не забыть добавить в документацию.

2024-05-27 07:39 UTC, dosymep commented on src/RevitFinishingWalls/Models/PluginConfig.cs
> +        public double WallBaseOffset { get; set; } = 0;
Надо бы единицу измерения добавить в название свойства.

2024-05-27 07:39 UTC, dosymep commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +        public IList<WallCreationData> GetWallCreationData(Room room, PluginConfig config) {
Стоит большие и сложные методы выводить в классы.

2024-05-27 09:33 UTC, vlastroG commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +                return new XYZ[] { curve.Evaluate(0.5, true) };
Тут не нормализованная линия, параметр

2024-05-27 09:40 UTC, vlastroG commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +        private Curve CombineCurves(Curve curveFirst, Curve curveSecond) {
То, что линии прямые должны быть и одна - продолжение другой, проверяется в вызывающем методе через вызов метода IsContinuation

2024-05-27 09:49 UTC, vlastroG commented on src/RevitFinishingWalls/Views/MainWindow.xaml
> +                <ComboBox ItemsSource="{Binding WallElevationModes}"
Заменил

2024-05-27 09:49 UTC, vlastroG commented on src/RevitFinishingWalls/ViewModels/WallTypeViewModel.cs
> +            _wallType = wallType;
Сделал проверку на null в конструкторе

2024-05-27 09:50 UTC, vlastroG commented on src/RevitFinishingWalls/ViewModels/MainViewModel.cs
> +        public string this[string columnName] {
Сделал сразу return

2024-05-27 09:51 UTC, vlastroG commented on src/RevitFinishingWalls/Services/Selection/SelectionFilterRooms.cs
Сделал проверку в AllowElement, в AllowReference всегда false

2024-05-27 09:52 UTC, vlastroG commented on src/RevitFinishingWalls/Resources/Converters/EnumDescriptionTypeConverter.cs
Убрал свой конвертер и сделал использование конвертера из платформы

2024-05-27 09:52 UTC, vlastroG commented on src/RevitFinishingWalls/ViewModels/MainViewModel.cs
> +                            if(offset < -5000) {
Сделал приветные константы для допусков

2024-05-27 09:52 UTC, vlastroG commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +            var views3D = new FilteredElementCollector(Document)
Добавил

2024-05-27 09:52 UTC, vlastroG commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +                return Array.Empty<Element>();
Скорректировал

2024-05-27 09:53 UTC, vlastroG commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +            } else {
Убрал

2024-05-27 09:53 UTC, vlastroG commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +        private bool IsContinuation(Curve first, Curve second) {
Дописал комментарий

2024-05-27 09:54 UTC, vlastroG commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +            } else if(borderEl != null) {
Скорректировал

2024-05-27 09:55 UTC, vlastroG commented on src/RevitFinishingWalls/Services/Creation/Implements/RoomFinisher.cs
> +            using(var transaction = _revitRepository.Document.StartTransaction("BIM: Создание отделочных стен")) {
Убрал BIM

2024-05-27 10:00 UTC, dosymep commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +                return new XYZ[] { curve.Evaluate(0.5, true) };
ага, я про это, типа единичная длина становится.
`Нормализация вектора — это преобразование заданного вектора в вектор в том же направлении (то есть в коллинеарный, параллельный вектор), но с единичной длиной.`

2024-05-27 10:00 UTC, vlastroG commented on src/RevitFinishingWalls/ViewModels/MainViewModel.cs
> +                _messageBoxService.Show(error, "BIM", MessageBoxButton.OK, MessageBoxImage.Warning, MessageBoxResult.OK);
99% ошибок - это несоединение стен, с ними ничего не поделаешь, только принять, поэтому кнопки ОК достаточно. Пользователю тут не нужен переход к ошибочным местам

2024-05-27 10:01 UTC, dosymep commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +        private Curve CombineCurves(Curve curveFirst, Curve curveSecond) {
надо бы такое явно сделать и лучше вывести в отдельный класс

2024-05-27 10:03 UTC, vlastroG commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +            const string defaultView3dName = "3D";
Если удален {3D} - это достаточно серьезный косяк в модели. Такого не должно быть в 99% случаев. По технологии имя 3D норм

2024-05-27 10:05 UTC, vlastroG commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +            switch(roomGetterMode) {
Методы небольшие и не будут расширяться, не думаю что разделение на классы улучшит читаемость кода

2024-05-27 10:06 UTC, dosymep commented on src/RevitFinishingWalls/ViewModels/MainViewModel.cs
> +                _messageBoxService.Show(error, "BIM", MessageBoxButton.OK, MessageBoxImage.Warning, MessageBoxResult.OK);
Месседж бокс может быть слишком длинным, и поэтому у тебя он может вылезти за экран и им не будет удобно пользоваться и понять в чем ошибка, так же ты там выводишь идентификаторы элементов, которые тоже не кликабельные и не рабочие, лишняя информация получается.

2024-05-27 10:08 UTC, dosymep commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +            const string defaultView3dName = "3D";
Где об этом написано? и почему именно 3d, а в других плагинах создание вида 3d, но там называется по другому?

2024-05-27 10:18 UTC, dosymep commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +        private Curve CombineCurves(Curve curveFirst, Curve curveSecond) {
> проверяется в вызывающем методе через вызов метода IsContinuation
а почему в том методе проверяется, что линии прямые? примыкать же могут любые кривые линии

2024-05-27 10:32 UTC, vlastroG commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +        public IList<WallCreationData> GetWallCreationData(Room room, PluginConfig config) {
Вынес метод GetWallCreationData в отдельный класс

2024-05-27 11:57 UTC, vlastroG commented on src/RevitFinishingWalls/Models/RevitRepository.cs
> +        private Curve CombineCurves(Curve curveFirst, Curve curveSecond) {
цель этих методов - схлопнуть прямой участок границы помещения, который образован несколькими отрезками. То есть сначала мне нужно проверить, что 2 отрезка лежат на одной прямой и являются продолжением друг друга. Если это так, то я их схлопываю в один и смотрю следующий отрезок и так далее пока не дойду до конца петли. Если текущий и следующий отрезки не лежат на одной прямой и не являются продолжением друг друга, то мне не нужно их схлопывать.
По итогу я сначала вызываю метод IsContinuation, если он возвращает true, я схлопываю отрезки через CombineCurves. То есть я не считаю, что метод CombineCurves должен схлопывать только отрезки, которые продолжают друг друга. Задачу по определению этого я перекладываю на вызывающий метод, который решает, надо ли ему что-то схлопывать или нет.

2024-05-27 12:36 UTC, vlastroG commented on src/RevitFinishingWalls/ViewModels/MainViewModel.cs
> +                _messageBoxService.Show(error, "BIM", MessageBoxButton.OK, MessageBoxImage.Warning, MessageBoxResult.OK);
Согласен, сделал отдельное окно для вывода ошибок

2024-05-29 12:22 UTC, dosymep requested changes
- было решено доработать окно вывода ошибок, сделать его относительно помещения.

2024-05-30 10:31 UTC, dosymep requested changes
- отключи панель группировки на гридах
- отключи разрешение редактирования на гридах
- думаю, стоит у помещений добавить больше показываемых параметров

Возможно стоит добавить группировку по типу ошибки? Создать колонку с коротким именем, а описание сделать более подробным?

2024-06-03 10:59 UTC, dosymep approved these changes

2024-06-03 10:59 UTC, merged