RevitReinforcementCoefficient: Разработан плагин расчета коэффициента армирования
Bim4Everyone/RevitPlugins pull request #49
Opened 2024-04-15 12:27 UTC by DivinN

Реализована первая версия плагина, дальнейшие работы будут произведены после тестирования и проверки расчетов этой версии BIM-координаторами

2024-05-27 11:14 UTC, dosymep requested changes

2024-05-27 11:14 UTC, dosymep commented on src/RevitReinforcementCoefficient/Models/ParamUtils.cs
> +                    flag = false;
Тут лучше сразу вернуть `false`, тогда тебе не понадобится этот `flag`

2024-05-27 11:14 UTC, dosymep commented on src/RevitReinforcementCoefficient/Models/ReportItem.cs
> +            if(!ElementIds.Contains(elementId)) {
Очень не производительный код, рекомендую его переделать.

2024-05-27 11:14 UTC, dosymep commented on src/RevitReinforcementCoefficient/Models/CalculationUtils.cs
> +        private readonly Dictionary<double, double> _massPerLengthDict = new Dictionary<double, double>() {
Напиши в документации по плагину, откуда эти числа и как их самому найти\посчитать.

2024-05-27 11:14 UTC, dosymep commented on src/RevitReinforcementCoefficient/Models/CalculationUtils.cs
> +        private readonly Dictionary<double, double> _overlapCoefDict = new Dictionary<double, double>() {
Напиши в документации по плагину, откуда эти числа и как их самому найти\посчитать.

2024-05-27 11:14 UTC, dosymep commented on src/RevitReinforcementCoefficient/Models/CalculationUtils.cs
> +            double volumeInInternal = element.get_Parameter(BuiltInParameter.HOST_VOLUME_COMPUTED).AsDouble();
Используй метод из платформы для получения значения параметра.

2024-05-27 11:14 UTC, dosymep commented on src/RevitReinforcementCoefficient/Models/CalculationUtils.cs
> +            int numberOfForm = _paramUtils.GetParamValueAnywhere<int>(rebar, "обр_ФОП_Форма_номер");
Вынеси названия параметров в константы

2024-06-11 09:37 UTC, DivinN commented on src/RevitReinforcementCoefficient/ViewModels/DesignTypeInfoVM.cs
> +        public void AddItem(Element elem) {
Выделить 3 класса - общий, для опалубки, для армирования

2024-06-11 13:32 UTC, DivinN commented on src/RevitReinforcementCoefficient/ViewModels/MainViewModel.cs
> +            DockPackages.Insert(0, _filterValueForNofiltering);
Не изменяется в процессе использования окна

2024-06-11 13:33 UTC, DivinN commented on src/RevitReinforcementCoefficient/Models/ParamUtils.cs
> +        public bool HasParamAnywhere(Element element, string paramName, ReportVM report) {
Не сработает, т.к. не все параметры могут быть внесены нормально в проект

2024-06-25 07:35 UTC, dosymep approved these changes

2024-06-25 07:38 UTC, merged