Конструктор секций: Добавлена первая версия плагина
Bim4Everyone/RevitPlugins pull request #50
Opened 2024-05-02 14:35 UTC by vlastroG

2024-06-05 11:30 UTC, dosymep requested changes
Посмотри в общем форматирование кода, много где лишние пропуски строк, и сортировку свойств.

2024-06-05 11:30 UTC, dosymep commented on src/RevitSectionsConstructor/Models/RevitRepository.cs
> +                .Where(group => group.GroupId == ElementId.InvalidElementId && group.Location is LocationPoint)
В платформе есть метод ElementId.IsNull()

2024-06-05 11:30 UTC, dosymep commented on src/RevitSectionsConstructor/Models/RevitRepository.cs
> +            XYZ currentLocation = (group.Group.Location as LocationPoint).Point;
Возможен NullReferenceException

2024-06-05 11:30 UTC, dosymep commented on src/RevitSectionsConstructor/Models/RevitRepository.cs
> +            var levelsForPlacing = group.LevelsForPlacing.Where(level => !level.Equals(group.CurrentLevel)).ToArray();
Каждый метод LINQ должен быть на новой строке

2024-06-05 11:30 UTC, dosymep commented on src/RevitSectionsConstructor/Services/GroupsHandler.cs
> +                            break;
Рекомендую тут выбрасывать OutOfRangeException

2024-06-05 11:30 UTC, dosymep commented on src/RevitSectionsConstructor/ViewModels/GroupViewModel.cs
> +                UpdateTopLevels(value);
Я бы это обновил через события и команды

2024-06-05 11:30 UTC, dosymep commented on src/RevitSectionsConstructor/ViewModels/GroupViewModel.cs
> +            for(int i = 0; i < enabledTopLevels.Length; i++) {
Тут умеснее foreach срау по итератору, без создания массива

2024-06-05 11:30 UTC, dosymep commented on src/RevitSectionsConstructor/ViewModels/GroupViewModel.cs
> +                    ActionOnGroup = ActionsOnGroup.Delete;
Не ясен код, т.е. в случае, если пользователь кнопку отожмет, то группа все равно удалится? Тут похоже есть баг

2024-06-05 11:30 UTC, dosymep commented on src/RevitSectionsConstructor/ViewModels/MainViewModel.cs
> +                ;
Точка с запятой потерялась :)

2024-06-05 11:30 UTC, dosymep commented on src/RevitSectionsConstructor/ViewModels/MainViewModel.cs
> +                && selectedGroupViewModels.Where(item => item is GroupViewModel).Count() > 0
Тут лучше использовать Any

2024-06-05 11:30 UTC, dosymep commented on src/RevitSectionsConstructor/ViewModels/MainViewModel.cs
> +            if(!_revitRepository.ActiveDocOnEmptySheet()) {
Рекомендую эту проверку вынести в класс `RevitSectionsConstructorCommand`

2024-06-07 07:00 UTC, vlastroG commented on src/RevitSectionsConstructor/Models/RevitRepository.cs
> +            XYZ currentLocation = (group.Group.Location as LocationPoint).Point;
Как раз для этого в методе GetPArentGroups я рассматриваю только те группы, у которых (Location is LocationPoint == true).
```
        public ICollection<Group> GetParentGroups() {
            return new FilteredElementCollector(Document)
                .OfCategory(BuiltInCategory.OST_IOSModelGroups)
                .OfClass(typeof(Group))
                .Where(group => group.GroupId == ElementId.InvalidElementId && group.Location is LocationPoint)
                .Cast<Group>()
                .ToArray();
        }
```

2024-06-07 07:02 UTC, vlastroG commented on src/RevitSectionsConstructor/Models/RevitRepository.cs
> +            XYZ currentLocation = (group.Group.Location as LocationPoint).Point;
Добавил также проверку на Location в метод CopyGroup

2024-06-07 07:10 UTC, vlastroG commented on src/RevitSectionsConstructor/Models/RevitRepository.cs
> +            var levelsForPlacing = group.LevelsForPlacing.Where(level => !level.Equals(group.CurrentLevel)).ToArray();
Сделал

2024-06-07 07:17 UTC, vlastroG commented on src/RevitSectionsConstructor/Services/GroupsHandler.cs
> +                            break;
Добавил выброс исключения NotSupportedException

2024-06-07 07:23 UTC, vlastroG commented on src/RevitSectionsConstructor/ViewModels/GroupViewModel.cs
> +            for(int i = 0; i < enabledTopLevels.Length; i++) {
Я тут использовал for чтобы точно сохранить порядок элементов, но забыл, что у меня IOrderedEnumerable, исправил на foreach

2024-06-07 08:07 UTC, vlastroG commented on src/RevitSectionsConstructor/ViewModels/GroupViewModel.cs
> +                    ActionOnGroup = ActionsOnGroup.Delete;
Добавил сброс удаления при снятии галочки

2024-06-07 08:09 UTC, vlastroG commented on src/RevitSectionsConstructor/ViewModels/MainViewModel.cs
> +                ;
подправил

2024-06-07 08:12 UTC, vlastroG commented on src/RevitSectionsConstructor/ViewModels/MainViewModel.cs
> +                && selectedGroupViewModels.Where(item => item is GroupViewModel).Count() > 0
сделал

2024-06-07 08:21 UTC, vlastroG commented on src/RevitSectionsConstructor/ViewModels/MainViewModel.cs
> +            if(!_revitRepository.ActiveDocOnEmptySheet()) {
сделал

2024-06-07 08:23 UTC, vlastroG commented on src/RevitSectionsConstructor/ViewModels/GroupViewModel.cs
> +                UpdateTopLevels(value);
думаю так сейчас оставить

2024-06-07 11:23 UTC, dosymep commented on src/RevitSectionsConstructor/Models/RevitRepository.cs
> +                .Where(group => group.GroupId == ElementId.InvalidElementId && group.Location is LocationPoint)
@vlastroG 
т.е. ты имеешь ввиду, что когда нет идентификатора группы, то это нормальная ситуация?

2024-06-07 11:26 UTC, dosymep commented on src/RevitSectionsConstructor/Models/RevitRepository.cs
> +            XYZ currentLocation = (group.Group.Location as LocationPoint).Point;
@vlastroG, если ты считаешь, что там всегда `LocationPoint`, тогда надо немного по другому писать

```csharp
XYZ currentLocation = (LocationPoint) group.Group.Location).Point;

```

2024-06-07 11:32 UTC, vlastroG commented on src/RevitSectionsConstructor/Models/RevitRepository.cs
> +                .Where(group => group.GroupId == ElementId.InvalidElementId && group.Location is LocationPoint)
я имею в виду, что если GroupId == InvalidElementId это нормальная ситуация, которая мне нужна. Если там по какой-то причине null, то мне этот элемент не нужен
![image](https://github.com/Bim4Everyone/RevitPlugins/assets/87359016/a198f0d9-180e-45f3-bed5-a9518ab3399c)

2024-06-07 11:37 UTC, dosymep commented on src/RevitSectionsConstructor/Services/GroupsHandler.cs
> +                            break;
@vlastroG, хорошо, тогда пусть текст сообщения будет более информативным, и в тексте исключение будет имя самого enum.

2024-06-07 11:38 UTC, vlastroG commented on src/RevitSectionsConstructor/Models/RevitRepository.cs
> +            XYZ currentLocation = (group.Group.Location as LocationPoint).Point;
![image](https://github.com/Bim4Everyone/RevitPlugins/assets/87359016/656fbaa6-263b-4fbe-917e-393e67418520)

хотя нет, уверен, поправил

2024-06-07 11:39 UTC, dosymep commented on src/RevitSectionsConstructor/Models/RevitRepository.cs
> +            XYZ currentLocation = (group.Group.Location as LocationPoint).Point;
@vlastroG в этом случае корректное исключение будет лучше нем непонятный NRE

2024-06-07 11:40 UTC, dosymep commented on src/RevitSectionsConstructor/Models/RevitRepository.cs
> +                .Where(group => group.GroupId == ElementId.InvalidElementId && group.Location is LocationPoint)
ясно, понял

2024-06-07 13:32 UTC, dosymep approved these changes
Отличная работа! Молодец

2024-06-07 13:32 UTC, merged