RevitApartmentPlans: Добавлен плагин "Планы квартир"
Bim4Everyone/RevitPlugins pull request #65
Opened 2024-07-03 13:31 UTC by vlastroG

2024-07-12 09:40 UTC, dosymep requested changes

2024-07-12 09:40 UTC, dosymep commented on src/RevitApartmentPlans/Converters/ViewTypeConverter.cs
> +    internal class ViewTypeConverter : MarkupExtension, IValueConverter {
Давай этот класс вынесем в общую папку ```dosymep``` и так же сделаем для всех типов видов

2024-07-12 09:40 UTC, dosymep commented on src/RevitApartmentPlans/Converters/ViewTypeConverter.cs
> +                    return null;
тут наверное стоит умирать :)

2024-07-12 09:40 UTC, dosymep commented on src/RevitApartmentPlans/Converters/ViewTypeConverter.cs
> +                    return null;
тут наверное стоит умирать :)

2024-07-12 09:40 UTC, dosymep commented on src/RevitApartmentPlans/Models/Apartment.cs
> +            Level level = rooms.First().Level;
думаю получение уровня лучше сделать через вид (если можно) и явно передавать его через конструктор

2024-07-12 09:40 UTC, dosymep commented on src/RevitApartmentPlans/Models/Apartment.cs
> +            if(rooms is null) { throw new ArgumentNullException(nameof(rooms)); }
лучше написать на разных строках, слишком много мешанины

2024-07-12 09:40 UTC, dosymep commented on src/RevitApartmentPlans/Models/PluginConfig.cs
> +        public string ParamName { get; set; }
можно идентификатор параметра (ParameterElement) сохранять, либо RevitParam

2024-07-12 09:40 UTC, dosymep commented on src/RevitApartmentPlans/Models/RevitRepository.cs
> +        /// <exception cref="ArgumentNullException"></exception>
рекомендую все такие полностью писать доку, либо вообще удалять

2024-07-12 09:40 UTC, dosymep commented on src/RevitApartmentPlans/Models/RevitRepository.cs
> +            ForgeTypeId[] paramTypes = { SpecTypeId.String.Text, new ForgeTypeId() };
у нас есть в платформе дефолтный [ForgeTypeId](https://dosymep.net/dosymep.Revit/api/2022/dosymep.Revit.ForgeTypeIdExtensions.html#dosymep_Revit_ForgeTypeIdExtensions_EmptyForgeTypeId)

2024-07-12 09:40 UTC, dosymep commented on src/RevitApartmentPlans/Models/RevitRepository.cs
> +                    throw new NotSupportedException($"Тип шаблона {template.ViewType} не поддерживается");
не хватает имени самого шаблона

2024-07-12 09:40 UTC, dosymep commented on src/RevitApartmentPlans/Services/BoundsCalculationService.cs
> +            var loop = _curveLoopsOffsetter.CreateOffsetLoop(_curveLoopsMerger.Merge(curveLoops), feetOffset);
стоит написать в несколько строк, чтобы промежуточные вычисления можно было посмотреть в дебаггере

2024-07-12 09:40 UTC, dosymep commented on src/RevitApartmentPlans/Services/CurveLoopsMerger.cs
> +        private bool TryMergeSolids(IList<Solid> solids, out Solid mergedSolid) {
у нас в платформе есть код объединения солидов [ссылка](https://dosymep.net/dosymep.Revit/api/2022/dosymep.Revit.Geometry.SolidExtensions.html#dosymep_Revit_Geometry_SolidExtensions_CreateUnitedSolids_System_Collections_Generic_IList_Autodesk_Revit_DB_Solid__)

2024-07-12 13:24 UTC, vlastroG commented on src/RevitApartmentPlans/Converters/ViewTypeConverter.cs
> +    internal class ViewTypeConverter : MarkupExtension, IValueConverter {
готово

2024-07-12 13:24 UTC, vlastroG commented on src/RevitApartmentPlans/Converters/ViewTypeConverter.cs
> +                    return null;
готово

2024-07-12 13:24 UTC, vlastroG commented on src/RevitApartmentPlans/Converters/ViewTypeConverter.cs
> +                    return null;
готово

2024-07-12 13:28 UTC, vlastroG commented on src/RevitApartmentPlans/Models/Apartment.cs
> +            Level level = rooms.First().Level;
У меня в логике плагина обрабатываются только помещения с активного плана с тем же уровнем что и у активного плана. Сейчас не может быть такой ситуации, что в одной квартире помещения с разных уровней, поэтому думаю уровень первого помещения брать для уровня квартиры это норм

2024-07-12 13:29 UTC, vlastroG commented on src/RevitApartmentPlans/Services/CurveLoopsOffsetter.cs
> +                return CurveLoop.CreateViaOffset(
готово

2024-07-12 13:30 UTC, vlastroG commented on src/RevitApartmentPlans/Models/RevitRepository.cs
> +        /// <exception cref="ArgumentNullException"></exception>
ты про документирование исключений?

2024-07-12 13:34 UTC, vlastroG commented on src/RevitApartmentPlans/Models/RevitRepository.cs
> +            ForgeTypeId[] paramTypes = { SpecTypeId.String.Text, new ForgeTypeId() };
готово

2024-07-12 13:40 UTC, vlastroG commented on src/RevitApartmentPlans/Services/CurveLoopsMerger.cs
> +            foreach(Face face in solid.Faces) {
готово, забываю про этот метод постоянно

2024-07-12 13:44 UTC, vlastroG commented on src/RevitApartmentPlans/Services/ViewPlanCreationService.cs
> +                    //Нельзя чтобы в контуре были дуги окружностей и т.п. Только прямые отрезки
готово

2024-07-12 13:49 UTC, vlastroG commented on src/RevitApartmentPlans/Services/ViewPlanCreationService.cs
> +                    progress.Report(++i);
скорректировал

2024-07-12 13:53 UTC, vlastroG commented on src/RevitApartmentPlans/Services/BoundsCalculationService.cs
> +            var loop = _curveLoopsOffsetter.CreateOffsetLoop(_curveLoopsMerger.Merge(curveLoops), feetOffset);
готово

2024-07-12 13:54 UTC, vlastroG commented on src/RevitApartmentPlans/Models/RevitRepository.cs
> +                    throw new NotSupportedException($"Тип шаблона {template.ViewType} не поддерживается");
готово

2024-07-12 13:56 UTC, vlastroG commented on src/RevitApartmentPlans/Models/Apartment.cs
> +            if(rooms is null) { throw new ArgumentNullException(nameof(rooms)); }
готово

2024-07-15 07:20 UTC, vlastroG commented on src/RevitApartmentPlans/Services/CurveLoopsMerger.cs
> +        private bool TryMergeSolids(IList<Solid> solids, out Solid mergedSolid) {
заменил метод

2024-07-15 07:40 UTC, vlastroG commented on src/RevitApartmentPlans/Models/RevitRepository.cs
> +        /// <exception cref="ArgumentNullException"></exception>
Добавил документацию

2024-07-15 07:56 UTC, dosymep approved these changes

2024-07-15 07:56 UTC, merged