RevitOpeningSlopes: Добавлен плагин откосы
Bim4Everyone/RevitPlugins pull request #67
Opened 2024-07-08 14:08 UTC by DiBrainz

Добавлен плагин для автоматического размещения семейства откосов по окнам

2024-07-10 06:25 UTC, dosymep requested changes

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/Models/Converters/EnumDescriptionTypeConverter.cs
> +        public object Convert(object value, Type targetType, object parameter, CultureInfo culture) {
этот конвертер уже [реализован](https://github.com/Bim4Everyone/RevitPlugins/blob/master/src/dosymep/EnumConverter.cs#L9)

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/Models/LinesFromOpening.cs
> +            XYZ dir1 = geomLine.Direction;
удали неиспользуемую переменную

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/Models/LinesFromOpening.cs
> +            ModelLine line = _revitRepository.Document.Create.NewModelCurve(geomLine, sketch) as ModelLine;
line тут не нужен

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/Models/NearestElements.cs
> +            ElementFilter categoryFilter = new ElementMulticategoryFilter(
фильтр можно закешировать

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +        private void CheckVectorDirection() {
тут не проверки, скорее перерасчет вектора направления окна, нейминг не очень

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/Models/SlopeCreationData.cs
> +        public Document Document { get; }
зачем тут документ?

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/Models/SlopeParams.cs
> +            Parameter heightParam = ElementExtensions.GetParam(slope, "Высота");
в платформе есть [методы](https://dosymep.net/dosymep.Revit/api/2024/dosymep.Revit.ElementExtensions.html#dosymep_Revit_ElementExtensions_SetParamValue_Autodesk_Revit_DB_Element_Autodesk_Revit_DB_BuiltInParameter_Autodesk_Revit_DB_ElementId_) по установке значений в параметры

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/Models/SlopeParams.cs
> +            Parameter heightParam = ElementExtensions.GetParam(slope, "Высота");
системные параметры нужно получать через BuiltInParameter

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/Models/SlopesDataGetter.cs
> +        public SlopesDataGetter(RevitRepository revitRepository) {
много лишних пустых строк

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/Models/SolidOperations.cs
> +                ElementFilter categoryFilter = new ElementMulticategoryFilter(
фильтр можно закешировать

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/README.md
> +Описание проекта
не написано описание проекта, не обновлен основной файл README.md

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/Services/CreationOpeningSlopes.cs
> +            error = sb.ToString();
ошибки лучше показывать через объектную модель в интерфейсе, какой элемент сломался, почему сломался, какие параметры из-за которых сломался. Вывод тысячи строк с рандомными числами пользователю не очень интересно смотреть.

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/Services/WindowSelectionFilter.cs
> +            return elem.Category.GetBuiltInCategory() == BuiltInCategory.OST_Windows;
есть специальный [метод](https://dosymep.net/dosymep.Revit/api/2024/dosymep.Revit.ElementExtensions.html#dosymep_Revit_ElementExtensions_InAnyCategory_Autodesk_Revit_DB_Element_Autodesk_Revit_DB_BuiltInCategory_) проверки принадлежности категории к BuilIntCategory

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/Services/WindowSelectionFilter.cs
> +            return true;
тут лучше вернуть false

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/ViewModels/MainViewModel.cs
> +            SlopeTypes = new ObservableCollection<SlopeTypeViewModel>(
получать и назначать объекты лучше в команде загрузки окна

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/ViewModels/MainViewModel.cs
> +        public string this[string columnName] {
мы по другому пишем код отображения ошибок, через CanExecute команды и выводом ошибки в свойство ErrorText

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/ViewModels/MainViewModel.cs
> +            using(var progressDialogService = ServicesProvider.GetPlatformService<IProgressDialogService>()) {
прогресс диалог нужно через DI настроить, и сразу все нужные свойства сделать по умолчанию

2024-07-10 06:25 UTC, dosymep commented on src/RevitOpeningSlopes/ViewModels/SlopeTypeViewModel.cs
> +        public string Name => _slopeType?.Name ?? string.Empty;
_slopeType - тут не может быть null, лучше добавь проверку в конструктор, что туда null не передали

2024-07-11 07:18 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/SlopeParams.cs
> +            Parameter heightParam = ElementExtensions.GetParam(slope, "Высота");
Используются параметры семейства

2024-07-11 07:28 UTC, DiBrainz commented on src/RevitOpeningSlopes/Services/CreationOpeningSlopes.cs
> +            error = sb.ToString();
Решили на следующий раз задачу оставить

2024-07-11 07:59 UTC, DiBrainz commented on src/RevitOpeningSlopes/ViewModels/MainViewModel.cs
> +            using(var progressDialogService = ServicesProvider.GetPlatformService<IProgressDialogService>()) {
Этот метод не работает без DevExpress

2024-07-11 08:40 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/AlreadySelectedWindowsGetter.cs
> +        public string Name => $"По предварительно выбранным окнам ({this.GetOpenings().Count})";
Исправил

2024-07-11 08:42 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/Converters/EnumDescriptionTypeConverter.cs
> +        public object Convert(object value, Type targetType, object parameter, CultureInfo culture) {
Удалил этот класс (реализовано без Enum)

2024-07-11 08:43 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/LinesFromOpening.cs
> +            XYZ dir1 = geomLine.Direction;
Удалил dir1

2024-07-11 08:43 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/LinesFromOpening.cs
> +            ModelLine line = _revitRepository.Document.Create.NewModelCurve(geomLine, sketch) as ModelLine;
Убрал line

2024-07-11 08:43 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/NearestElements.cs
> +            ElementFilter categoryFilter = new ElementMulticategoryFilter(
Закешировал фильтр

2024-07-11 08:43 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +        private void CheckVectorDirection() {
Переименовал метод

2024-07-11 08:44 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/SlopeCreationData.cs
> +        public Document Document { get; }
Удалил неиспользуемое свойство

2024-07-11 08:44 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/SlopeParams.cs
> +            Parameter heightParam = ElementExtensions.GetParam(slope, "Высота");
Переделал под методы платформы

2024-07-11 08:44 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/SlopesDataGetter.cs
> +        public SlopesDataGetter(RevitRepository revitRepository) {
Убрал лишние строки

2024-07-11 08:44 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/SolidOperations.cs
> +                ElementFilter categoryFilter = new ElementMulticategoryFilter(
Закешировал фильтр

2024-07-11 08:45 UTC, DiBrainz commented on src/RevitOpeningSlopes/README.md
> +Описание проекта
Добавил описание проекта и добавил строку в основной README.md

2024-07-11 08:45 UTC, DiBrainz commented on src/RevitOpeningSlopes/Services/WindowSelectionFilter.cs
> +            return elem.Category.GetBuiltInCategory() == BuiltInCategory.OST_Windows;
Переделал под специальный метод

2024-07-11 08:45 UTC, DiBrainz commented on src/RevitOpeningSlopes/Services/WindowSelectionFilter.cs
> +            return true;
Исправил

2024-07-11 08:46 UTC, DiBrainz commented on src/RevitOpeningSlopes/ViewModels/MainViewModel.cs
> +            SlopeTypes = new ObservableCollection<SlopeTypeViewModel>(
Перекинул в метод LoadConfig()

2024-07-11 08:47 UTC, DiBrainz commented on src/RevitOpeningSlopes/ViewModels/MainViewModel.cs
> +        public string this[string columnName] {
Переделал код и добавил в CanAcceptView(), удалил лишнее

2024-07-11 08:47 UTC, DiBrainz commented on src/RevitOpeningSlopes/ViewModels/SlopeTypeViewModel.cs
> +        public string Name => _slopeType?.Name ?? string.Empty;
Исправил проверку

2024-07-12 07:39 UTC, dosymep requested changes

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Services/CreationOpeningSlopes.cs
> +namespace RevitOpeningSlopes.Models.Services {
исправь пространство имен (проверь сразу во всех файлах)

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Services/CreationOpeningSlopes.cs
> +                    progress.Report(i++);
возможен NRE

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Services/ICreationOpeningSlopes.cs
> +        void CreateSlopes(PluginConfig config,
комментарий не полный, не хватает описания некоторых параметров

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/ViewModels/MainViewModel.cs
> +            CreationOpeningSlopes creationOpeningSlopes,
зачем создавал интерфейс ICreationOpeningSlopes?

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/RevitOpeningSlopesCommand.cs
> +            using(IKernel kernel = uiApplication.CreatePlatformServices()) {
не все создаваемые классы контейнером настроены

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/SolidOperations.cs
> +        private ElementFilter CategoryFilter => new ElementMulticategoryFilter(
лучше сделай приватное поле, у тебя при каждом получении значения свойства будет создаваться новый экземпляр фильтра

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/SlopesDataGetter.cs
> +                + _revitRepository.ConvertToFeet(double.Parse(config.SlopeFrontOffset));
ты уверен, что тут будет всегда число? может стоит свойство конфига сделать типом double?

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/SlopeParams.cs
> +            ElementExtensions.SetParamValue(slope, "Высота", slopeCreationData.Height);
это эксеншен методы, их нужно использовать как обычные методы экземпляра

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/RevitRepository.cs
> +                .Where(el => el is Element)
что это за странная конструкция?

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/RevitRepository.cs
> +                .Where(el => el is Element)
что это за странная конструкция?

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/RevitRepository.cs
> +                .Where(id => Document.GetElement(id).Category.GetBuiltInCategory()
в платформе есть метод для этого

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/PluginConfig.cs
> +        public string SlopeFrontOffset { get; set; } //Вылет откоса от фасада здания наружу
комментарии лучше писать по стандарту

в имени числовых значений лучше указывать единицу измерения (это миллиметры, метры или вообще углы?)

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +            //Запуск функции для проверки правильного направления вектора семейства окна
это не проверка

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +        /// Проверка вектора окна, размещенного в проекте и установка направления вектора окна в сторону от фасада
это не проверка

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +            }
пустые строки по коду поищи, их где надо надо добавить, где надо надо удалить

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                    //Создание линии вправо и разделения ее на точки для запуска массива линий из этих точек
пробел нужен после символов //

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                                _openingDepthPoint = intersectCoord;
а тебе какой вариант точки нужен, первый или последний? напиши комментарий

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                    backwardLineFromOffsetPoint.ComputeClosestPoints(lineFromDepthPointToLeft, true, false, false,
напиши каждый параметр на новой строке

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                                out closestPoints);
эту переменную можно объявить сразу тут же ``` out IList<ClosestPointsPairBetweenTwoCurves> closestPoints```

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                    _centralOpeningDepthPoint = closestPoints.FirstOrDefault().XYZPointOnFirstCurve;
возможно NRE

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +        /// <exception cref="ArgumentException"></exception>
удали тег исключений, если не описал когда он выбрасывается

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                    IList<ClosestPointsPairBetweenTwoCurves> closestPoints =
тут тоже не забудь поправить

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                    IList<ClosestPointsPairBetweenTwoCurves> closestPoints =
тут не забудь поправить

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                            }
не забудь написать коммент

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +        /// <exception cref="ArgumentException"></exception>
не забудь удалить или дописать

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +        /// <exception cref="ArgumentException"></exception>
не забудь удалить или дописать

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +        /// <exception cref="ArgumentException"></exception>
не забудь удалить или дописать

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                return _rotationAngle;
тут в случае если код не попадет в условие, то вернется не понятное значение ```_rotationAngle```

2024-07-12 07:39 UTC, dosymep commented on src/RevitOpeningSlopes/Models/NearestElements.cs
> +        private ElementFilter CategoryFilter => new ElementMulticategoryFilter(
при каждом вызове свойства будут возвращаться новые экземпляры, тут лучше поле сделать

2024-07-16 09:30 UTC, DiBrainz commented on src/RevitOpeningSlopes/Services/CreationOpeningSlopes.cs
> +namespace RevitOpeningSlopes.Models.Services {
Исправил

2024-07-16 09:31 UTC, DiBrainz commented on src/RevitOpeningSlopes/Services/ICreationOpeningSlopes.cs
> +        void CreateSlopes(PluginConfig config,
Сделал новое описание

2024-07-16 09:31 UTC, DiBrainz commented on src/RevitOpeningSlopes/ViewModels/MainViewModel.cs
> +            CreationOpeningSlopes creationOpeningSlopes,
Удалил за ненадобностью

2024-07-16 09:32 UTC, DiBrainz commented on src/RevitOpeningSlopes/RevitOpeningSlopesCommand.cs
> +            using(IKernel kernel = uiApplication.CreatePlatformServices()) {
Добавил нужные классы

2024-07-16 09:32 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/SolidOperations.cs
> +        private ElementFilter CategoryFilter => new ElementMulticategoryFilter(
Исправил на приватное поле

2024-07-16 09:32 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/PluginConfig.cs
> +        public string SlopeFrontOffset { get; set; } //Вылет откоса от фасада здания наружу
Скорректировал комментарии

2024-07-16 09:33 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +            //Запуск функции для проверки правильного направления вектора семейства окна
Переименовал

2024-07-16 09:33 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +        /// Проверка вектора окна, размещенного в проекте и установка направления вектора окна в сторону от фасада
Переименовал

2024-07-16 09:33 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +            }
Скорректировал пустые строки

2024-07-16 09:33 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                    //Создание линии вправо и разделения ее на точки для запуска массива линий из этих точек
Изменил комментарии

2024-07-16 09:33 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                                _openingDepthPoint = intersectCoord;
Добавил комментарий

2024-07-16 09:33 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                    backwardLineFromOffsetPoint.ComputeClosestPoints(lineFromDepthPointToLeft, true, false, false,
Скорректировал переносы

2024-07-16 09:34 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                                out closestPoints);
Тут же не получается, исключение ArgumentNullException, оставил как было отдельной строкой

2024-07-16 09:35 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +        /// <exception cref="ArgumentException"></exception>
Добавил описание для тега исключения

2024-07-16 09:35 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                    IList<ClosestPointsPairBetweenTwoCurves> closestPoints =
Скорректировал переносы строк

2024-07-16 09:35 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                    IList<ClosestPointsPairBetweenTwoCurves> closestPoints =
Скорректировал переносы строк

2024-07-16 09:35 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                            }
Написал коммент

2024-07-16 09:35 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +        /// <exception cref="ArgumentException"></exception>
Написал комментарий

2024-07-16 09:36 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +        /// <exception cref="ArgumentException"></exception>
Написал комментарий

2024-07-16 09:36 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +        /// <exception cref="ArgumentException"></exception>
Написал комментарий

2024-07-16 09:37 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                return _rotationAngle;
Были установлены значения по умолчанию для таких случаев
![image](https://github.com/user-attachments/assets/8172f7c6-f11f-439e-b5f9-9483c94f7a5e)

2024-07-16 09:37 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/NearestElements.cs
> +        private ElementFilter CategoryFilter => new ElementMulticategoryFilter(
Сделал приватное поле

2024-07-16 12:54 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/RevitRepository.cs
> +                .Where(el => el is Element)
Переделал

2024-07-16 12:54 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/RevitRepository.cs
> +                .Where(el => el is Element)
Переделал

2024-07-16 13:22 UTC, DiBrainz commented on src/RevitOpeningSlopes/Services/CreationOpeningSlopes.cs
> +                    progress.Report(i++);
Проверил, всё в порядке, можно обсудить

2024-07-16 14:20 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                    _centralOpeningDepthPoint = closestPoints.FirstOrDefault().XYZPointOnFirstCurve;
Тут при таких условиях не будет null, в других методах по поиску точек есть проверки на null, в случае чего выбрасывается исключение и данное окно не обрабатывается, но это можно обсудить

2024-07-16 14:42 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/SlopesDataGetter.cs
> +                + _revitRepository.ConvertToFeet(double.Parse(config.SlopeFrontOffset));
Тут всегда будет число, так как проверка не позволит пользователю запустить плагин

2024-07-16 14:47 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/SlopeParams.cs
> +            ElementExtensions.SetParamValue(slope, "Высота", slopeCreationData.Height);
Поправил

2024-07-17 08:33 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/RevitRepository.cs
> +                .Where(id => Document.GetElement(id).Category.GetBuiltInCategory()
Исправил с использованием методов расширения

2024-07-18 10:49 UTC, dosymep requested changes

2024-07-18 10:49 UTC, dosymep commented on src/RevitOpeningSlopes/Models/LinesFromOpening.cs
> +    [Transaction(TransactionMode.Manual)]
удали этот атрибут, это не команда ревита, он тут явно лишний

2024-07-18 10:49 UTC, dosymep commented on src/RevitOpeningSlopes/Models/SlopesDataGetter.cs
> +                + _revitRepository.ConvertToFeet(double.Parse(config.SlopeFrontOffset));
может все таки стоит сделать свойство конфига числом?

2024-07-18 10:49 UTC, dosymep commented on src/RevitOpeningSlopes/RevitOpeningSlopesCommand.cs
> +                    .InSingletonScope();
ты уверен, что все классы требуется делать синглтонами?

2024-07-18 10:49 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                                _openingDepthPoint = intersectCoord;
верни значение, у тебя цикл продолжается после нахождения нужной точки.

2024-07-18 10:49 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                    _centralOpeningDepthPoint = closestPoints.FirstOrDefault().XYZPointOnFirstCurve;
если у тебя тут 100% не будет null, тогда надо использовать метод First

2024-07-18 10:49 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                    IList<ClosestPointsPairBetweenTwoCurves> closestPoints =
ты создаешь экземпляр класса, который потом нигде не используется, объяви лист сразу в out параметре, исправь везде
`IList<ClosestPointsPairBetweenTwoCurves> closestPoints =
                        new List<ClosestPointsPairBetweenTwoCurves>();`

2024-07-18 10:49 UTC, dosymep commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                return _rotationAngle;
даже с таким присвоением, значение ноль валидное?
судя по первому условию нет `_rotationAngle > 0 `, получается, у тебя в случаях, когда будет значение ноль, код расчета всегда будет выполнятся

2024-07-23 08:47 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                                _openingDepthPoint = intersectCoord;
Поправил комментарий

2024-07-23 08:52 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                    _centralOpeningDepthPoint = closestPoints.FirstOrDefault().XYZPointOnFirstCurve;
Переделал

2024-07-23 08:53 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                    IList<ClosestPointsPairBetweenTwoCurves> closestPoints =
По другому не получится объявить переменную внутри метода ComputeClosestPoints (обсуждали)

2024-07-23 08:55 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/LinesFromOpening.cs
> +    [Transaction(TransactionMode.Manual)]
Удалил

2024-07-23 08:56 UTC, DiBrainz commented on src/RevitOpeningSlopes/RevitOpeningSlopesCommand.cs
> +                    .InSingletonScope();
Оставил синглтонами

2024-07-23 14:21 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/OpeningHandler.cs
> +                return _rotationAngle;
Убрал лишнюю проверку

2024-07-23 14:23 UTC, DiBrainz commented on src/RevitOpeningSlopes/Models/SlopesDataGetter.cs
> +                + _revitRepository.ConvertToFeet(double.Parse(config.SlopeFrontOffset));
Сделал свойство конфига nallable double

2024-07-26 08:19 UTC, dosymep approved these changes

2024-07-26 08:19 UTC, merged