RevitDeclarations: Добавлен плагин "Декларации"
Bim4Everyone/RevitPlugins pull request #68
Opened 2024-07-09 09:16 UTC by sssenya

Добавлен новый плагин "Декларации".
Плагин позволяет выгружать из проектов Revit декларации по квартирам в формате Excel или json.
Декларация это таблица с информацией по квартире и её помещениям. Часть данные берется из параметров помещений, часть рассчитывается скриптом (например, УТП - уникальные торговые предложения).

2024-07-10 11:19 UTC, dosymep requested changes

2024-07-10 11:19 UTC, dosymep commented on src/RevitDeclarations/Models/RevitRepository.cs
> +            ElementPhaseStatusFilter phaseFilter = new ElementPhaseStatusFilter(phase.Id, statuses);
если метод часто вызывается, тогда фильтры можно закешировать

2024-07-10 11:19 UTC, dosymep commented on src/RevitDeclarations/Models/RevitRepository.cs
> +                .Where(x => x.Symbol.Family.Name.ToLower().Contains("ванна") ||
может быть есть смысл вывести эти слова в конфиг?

2024-07-10 11:19 UTC, dosymep commented on src/RevitDeclarations/Models/RevitRepository.cs
> +                .Where(x => x.Symbol.Family.Name.ToLower().Contains("ванна") ||
ну хотя наверное это жозенько, если гуи еще к этому создавать :)

2024-07-10 11:19 UTC, dosymep commented on src/RevitDeclarations/Models/RoomContours/ContourCheckEnum.cs
> +    public static class EnumExtensions {
у нас в платформе есть конвертеры для показа енамов в gui

2024-07-10 11:19 UTC, dosymep commented on src/RevitDeclarations/Models/RoomForChecks.cs
> +        public bool HasParameter(Parameter parameter) {
в платформе есть метод проверки существования параметра в элементе

2024-07-10 11:19 UTC, dosymep commented on src/RevitDeclarations/Models/RoomForChecks.cs
> +        public bool HasParameter(Parameter parameter) {
возможно класс даже не нужен будет для этого :)

2024-07-10 11:19 UTC, dosymep commented on src/RevitDeclarations/Models/Settings/DeclarationSettings.cs
> +        public Parameter FilterRoomsParam => ParametersVM.SelectedFilterRoomsParam;
по-хорошему должно быть наоборот, внутри VM модель настроек

2024-07-10 11:19 UTC, dosymep commented on src/RevitDeclarations/Models/UtpCalculator.cs
> +            ErrorsListViewModel areaErrorListVM = new ErrorsListViewModel() {
по-хорошему в модели не должно быть VM, но тут не сильно критично :)

2024-07-10 11:19 UTC, dosymep commented on src/RevitDeclarations/Models/UtpCalculator.cs
> +                if(height < 3400) {
хотелось бы тут комментарий, что это за число и откуда оно взялось, а лучше вывести это в конфиг либо в константы

2024-07-10 11:19 UTC, dosymep commented on src/RevitDeclarations/Models/UtpCalculator.cs
> +        public string CalculateHighflat(Apartment apartment) {
методы по логике тут не расчитывают что-то, а скорее всего возвращают какое-то значение, которое для отображения в GUI, возможно стоит их всех вывести в конвертеры?

2024-07-10 11:19 UTC, dosymep commented on src/RevitDeclarations/RevitDeclarations.csproj
> +        <HintPath>..\..\..\..\..\..\..\..\..\Windows\assembly\GAC_MSIL\Microsoft.Office.Interop.Excel\15.0.0.0__71e9bce111e9429c\Microsoft.Office.Interop.Excel.dll</HintPath>
странно как-то библиотека подключилась, возможно будут проблемы с ней при сборке на другом компе, так же кстати, так как ты используешь 15 версию Excel у себя, то наверное стоит в инициализации Excel прописать нужную версию (желательно ниже максимальной, посмотри про версии экселя)

2024-07-10 11:19 UTC, dosymep commented on src/RevitDeclarations/RevitDeclarationsCommand.cs
> +        protected override void Execute(UIApplication uiApplication) {
было бы максимально круто, если бы ты использовал по полной DI контейнер :)

2024-07-10 11:25 UTC, dosymep requested changes
- есть пара моментов с конфигом, надо что-то с ними сделать, в них сохранять не надо имена параметров с учетом локализации, если это не экспорт пользователю (но я там вроде написал для конфига плагина)
- есть еще проблемка с ответственностями, по хорошему в модели не должно быть VM
- есть проблемы с компаратором, по хорошему ты в словарик мог его засунуть и не парится с Lower

не забудь решить конфликты, прими оба изменения

2024-07-11 16:40 UTC, sssenya commented on src/RevitDeclarations/Models/Priorities/RoomPriority.cs
> +        public bool IsOther { get; set; } = false;
это свойство для приоритетов, которых не было в конфиге изначально
они создаются на основе файла Revit, если найдены помещения с именами не из конфига
переименовал на IsNonConfig

2024-07-11 16:41 UTC, sssenya commented on src/RevitDeclarations/Models/RevitRepository.cs
> +                .Where(x => x.Symbol.Family.Name.ToLower().Contains("ванна") ||
это обсуждали с архитекторами, но решили так оставить

2024-07-12 09:09 UTC, sssenya commented on src/RevitDeclarations/Models/Apartment.cs
> +            string name = priority.NameLower;
Такого быть не должно, это базовая логика скрипта, что есть лишние имена, которых изначально не было в списке приоритетов
и они добавляются в отдельную группу

2024-07-16 08:16 UTC, sssenya commented on src/RevitDeclarations/Models/RevitRepository.cs
> +            ElementPhaseStatusFilter phaseFilter = new ElementPhaseStatusFilter(phase.Id, statuses);
Используется от одного до примерно 10 раз при одном запуске скрипта. Есть смысл кешировать?

2024-07-19 06:25 UTC, dosymep requested changes

2024-07-19 06:25 UTC, dosymep commented on src/RevitDeclarations/Models/Export/JsonExporter.cs
> +            ISerializationService service = ServicesProvider.GetPlatformService<ISerializationService>();
думаю сериализатор стоит закешировать в поле класса, так же есть метод `Path.ChangeExtension` (посмотри может он подойдет)

2024-07-19 06:25 UTC, dosymep commented on src/RevitDeclarations/Models/Export/JsonImporter.cs
> +                    elements = service.Deserialize<List<T>>(allText);
сразу верни нужный результат

2024-07-19 07:25 UTC, dosymep requested changes

2024-07-19 07:25 UTC, dosymep commented on src/RevitDeclarations/Models/Export/JsonImporter.cs
> +                    ISerializationService service = ServicesProvider.GetPlatformService<ISerializationService>();
Вынеси сервис в поле

2024-07-19 07:25 UTC, dosymep commented on src/RevitDeclarations/Models/Export/JsonImporter.cs
> +                    ErrorInfo = $"Ошибка сериализации json файла: {e.Message}";
переделай на исключения

2024-07-19 08:47 UTC, dosymep approved these changes

2024-07-19 08:48 UTC, merged