RevitClashDetective: В навигатор коллизий добавлен вывод % пересечения и объема коллизии
Bim4Everyone/RevitPlugins pull request #71
Opened 2024-07-19 13:06 UTC by vlastroG

В GUI просмотра коллизий добавлены столбцы:
- % пересечения относительно меньшего элемента
- объем пересечения в м³

![image](https://github.com/user-attachments/assets/6f2c9fb6-2c0f-45fe-9e1c-d6b138db4da0)

2024-07-23 06:20 UTC, dosymep requested changes

2024-07-23 06:20 UTC, dosymep commented on src/RevitClashes/Models/Clashes/ClashData.cs
> +            return MainElementVolume == other.MainElementVolume
сравнение `double` не очень хорошая затея

2024-07-23 06:20 UTC, dosymep commented on src/RevitClashes/Models/Clashes/ClashModel.cs
> +        private List<Solid> GetMainSolids() {
думаю этот метод лучше положить в `ElementModel`

2024-07-23 06:20 UTC, dosymep commented on src/RevitClashes/Models/Clashes/ClashModel.cs
> +        private List<Solid> GetOtherSolids() {
думаю этот метод лучше положить в `ElementModel`

2024-07-23 06:20 UTC, dosymep commented on src/RevitClashes/Models/Clashes/ClashModel.cs
> +        private Transform GetMainTransform() {
думаю этот метод лучше положить в `ElementModel`

2024-07-23 06:20 UTC, dosymep commented on src/RevitClashes/Models/Clashes/ClashModel.cs
> +
думаю этот метод лучше положить в `ElementModel`

2024-07-23 06:20 UTC, dosymep commented on src/RevitClashes/Models/Clashes/ClashModel.cs
> +                double mainSolidsV = mainSolids.Sum(s => s.Volume);
думаю этот метод лучше положить в `ElementModel`

2024-07-23 06:20 UTC, dosymep commented on src/RevitClashes/Models/Clashes/ClashModel.cs
> +                double otherSolidsV = otherSolids.Sum(s => s.Volume);
думаю этот метод лучше положить в `ElementModel`

2024-07-23 07:58 UTC, vlastroG commented on src/RevitClashes/Models/Clashes/ClashModel.cs
> +
перенес в ElementModel

2024-07-23 07:58 UTC, vlastroG commented on src/RevitClashes/Models/Clashes/ClashModel.cs
> +        private Transform GetMainTransform() {
перенес в ElementModel

2024-07-23 07:59 UTC, vlastroG commented on src/RevitClashes/Models/Clashes/ClashData.cs
> +            return MainElementVolume == other.MainElementVolume
сделал через допуск разницы чисел по модулю

2024-07-23 08:01 UTC, vlastroG commented on src/RevitClashes/Models/Clashes/ClashModel.cs
> +                double mainSolidsV = mainSolids.Sum(s => s.Volume);
оставил получение объемов через сумму солидов, полученных при вызове ElementModel.GetSolids()

2024-07-23 08:02 UTC, vlastroG commented on src/RevitClashes/Models/Clashes/ClashModel.cs
> +        private List<Solid> GetMainSolids() {
вынес получение солидов в координатах самих ElementModel внутрь ElementModel, трансформацию солидов для обработки коллизии оставил в ClashModel

2024-07-23 08:03 UTC, vlastroG commented on src/RevitClashes/Models/Clashes/ClashModel.cs
> +        private List<Solid> GetOtherSolids() {
вынес получение солидов в координатах самих ElementModel внутрь ElementModel, трансформацию солидов для обработки коллизии оставил в ClashModel

2024-07-26 08:01 UTC, dosymep requested changes

2024-07-26 08:01 UTC, dosymep commented on src/RevitClashes/Models/Clashes/ElementModel.cs
> +                ?? throw new ArgumentNullException(
тут скорее уместнее выбросить просто `ArgumentException`

2024-07-26 08:17 UTC, vlastroG commented on src/RevitClashes/Models/Clashes/ClashModel.cs
> +                throw new ArgumentNullException(
скорректировал

2024-07-26 08:21 UTC, dosymep approved these changes

2024-07-26 08:28 UTC, merged