RevitServerFolders: Обновление плагина
Bim4Everyone/RevitPlugins pull request #77
Opened 2024-08-06 12:46 UTC by vlastroG

2024-08-08 11:49 UTC, dosymep requested changes
- надо разобраться с локером, подозрительное место как по мне
- при раскрытии узла должна быть загрузка элементов, а то пользователь потеряется

2024-08-08 12:42 UTC, vlastroG commented on src/RevitServerFolders/ViewModels/MainViewModel.cs
> +                lock(_locker) {
При выборе папки источника помимо команды OpenFromFoldersCommand срабатывает команда SourceFolderChangedCommand, которая привязана к событию изменения пути к папке в контроле. Эти 2 команды вызывают метод AddModelObjects, через который добавляются модели в коллекцию ModelObjects. Без локера 2 команды могут задвоить список моделей, т.к. ModelObjects.Add у обоих команд вызовется после обоих вызовов метода Models.Clear()

2024-08-08 12:46 UTC, vlastroG commented on src/RevitServerFolders/ViewModels/Rs/RsModelObjectViewModel.cs
> +            if(CancellationTokenSource.IsCancellationRequested) {
скорректировал

2024-08-08 12:46 UTC, vlastroG commented on src/RevitServerFolders/ViewModels/Rs/RsModelObjectViewModel.cs
>          private async Task ReLoadChildrenObjects() {
сделал

2024-08-08 14:07 UTC, vlastroG commented on src/RevitServerFolders/ViewModels/MainViewModel.cs
> +                lock(_locker) {
Заменил lock на пропуск второй команды

2024-08-13 07:47 UTC, dosymep requested changes
Надо бы логгер добавить, тогда хотя бы сможем в телеметрии и в журнале ревита видеть какие были проблемы. Добавь название файла, и исключение, посмотри, может быть имеет смысл еще какие-нибудь свойства добавить.

2024-08-13 07:47 UTC, dosymep commented on src/RevitServerFolders/Services/NwcExportService.cs
> +                    // pass
кстати, точно, у нас есть логгер, попробуй тут его использовать и ошибки записывать сюда (надо настроить DI и в него прокинуть логгер, логгер возьми из команды ревит)

2024-08-13 07:47 UTC, dosymep commented on src/RevitServerFolders/Services/RvtExportService.cs
> +                    // pass
тут тоже про логгер не забудь :)

2024-08-13 07:47 UTC, dosymep commented on src/RevitServerFolders/ViewModels/Rs/RsModelObjectViewModel.cs
> +        private protected readonly IServerClient _serverClient;
зачем `private`?

2024-08-13 07:47 UTC, dosymep commented on src/RevitServerFolders/Views/MainWindow.xaml
> +                Binding="{Binding SkipObject, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged, Converter={StaticResource InverseBooleanConverter}}"
я обычно длинные биндинги пишу на несколько строк

2024-08-13 08:39 UTC, vlastroG commented on src/RevitServerFolders/Views/MainWindow.xaml
> +                Binding="{Binding SkipObject, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged, Converter={StaticResource InverseBooleanConverter}}"
скорректировал

2024-08-13 08:42 UTC, vlastroG commented on src/RevitServerFolders/ViewModels/Rs/RsModelObjectViewModel.cs
> +        private protected readonly IServerClient _serverClient;
private protected привык писать для полей, которые нужно открывать наследникам. И у нас в editorconfig префикс с нижним подчеркиванием только для приватных полей, сейчас предупреждение показывается для названия поля. Крч private убрал

2024-08-13 08:43 UTC, vlastroG commented on src/RevitServerFolders/Services/RvtExportService.cs
> +                    // pass
добавил

2024-08-13 08:44 UTC, vlastroG commented on src/RevitServerFolders/Services/NwcExportService.cs
> +                    // pass
добавил

2024-08-13 09:03 UTC, dosymep commented on src/RevitServerFolders/Services/NwcExportService.cs
> +                    // pass
я про логгер писал, который в команде ревит, а не из платформы

2024-08-13 09:31 UTC, vlastroG commented on src/RevitServerFolders/Services/NwcExportService.cs
> +                    // pass
сделал получение логгера из свойства класса команды

2024-08-13 09:31 UTC, vlastroG commented on src/RevitServerFolders/Services/RvtExportService.cs
> +                    // pass
сделал получение логгера из свойства класса команды

2024-08-14 07:08 UTC, dosymep requested changes

2024-08-14 07:08 UTC, dosymep commented on src/RevitServerFolders/Services/NwcExportService.cs
> +            _loggerService.Information($"Event handler: {nameof(UIApplicationOnDialogBoxShowing)}");
добавь какую-нибудь доп инфу, что за эвент был и тп

2024-08-14 07:08 UTC, dosymep commented on src/RevitServerFolders/Services/NwcExportService.cs
> +            _loggerService.Information($"Event handler: {nameof(ApplicationOnFailuresProcessing)}");
тут добавь, хотя бы количество предупреждений и количество ошибок, может еще что-нибудь

2024-08-14 12:19 UTC, vlastroG commented on src/RevitServerFolders/Services/NwcExportService.cs
> +            _loggerService.Information($"Event handler: {nameof(UIApplicationOnDialogBoxShowing)}");
Добавил логгирование свойства DialogBoxShowingEventArgs.DialogId. Как тут вытащить сообщение ошибки из этого окна диалога хз

2024-08-14 12:21 UTC, vlastroG commented on src/RevitServerFolders/Services/NwcExportService.cs
> +            _loggerService.Information($"Event handler: {nameof(ApplicationOnFailuresProcessing)}");
Добавил логгирование сообщений об ошибках с их количеством. Также добавил логгирование, если удаление 
 проблемных элементов не выполнилось

2024-08-14 12:26 UTC, vlastroG commented on src/RevitServerFolders/Services/NwcExportService.cs
> +            _loggerService.Information($"Event handler: {nameof(UIApplicationOnDialogBoxShowing)}");
![image](https://github.com/user-attachments/assets/a4e23e7f-ccb9-4bb5-9216-f0ad9dfd59af)
надеюсь ревит тут всегда пишет сообщение из окна диалога

2024-08-22 08:34 UTC, dosymep approved these changes

2024-08-22 08:34 UTC, merged