RevitValueModifier: Добавлен плагин "Изменить значение"
Bim4Everyone/RevitPlugins pull request #88
Opened 2024-10-01 16:12 UTC by DivinN

Разработан плагин по переносу значений одного параметр (параметров) в другой параметр с учетом префиксов/суффиксов и т.п.

2024-10-02 07:52 UTC, dosymep requested changes

2024-10-02 07:52 UTC, dosymep commented on .nuke/parameters.RevitValueModifier.json
Плагин точно будет на вкладке КР?

2024-10-02 07:52 UTC, dosymep commented on src/RevitValueModifier/Localization/Language.en-US.xaml
> +    <system:String x:Key="MainWindow.Title">Example command</system:String>
измени название окна

2024-10-02 07:52 UTC, dosymep commented on src/RevitValueModifier/Localization/Language.ru-RU.xaml
> +    <system:String x:Key="MainWindow.Title">Пример команды</system:String>
измени название окна

2024-10-02 07:52 UTC, dosymep commented on src/RevitValueModifier/ViewModels/MainViewModel.cs
> +            _timerByChangedMask.Tick += (s, e) => {
сделай отдельным методом

2024-10-02 07:52 UTC, dosymep commented on src/RevitValueModifier/ViewModels/MainViewModel.cs
> +            using(Transaction transaction = _revitRepository.Document.StartTransaction("Изменение значений параметров")) {
переведи название транзакции

2024-10-02 07:52 UTC, dosymep commented on src/RevitValueModifier/Models/PluginConfig.cs
> +        public string TaskForWrite { get; set; }
название свойства не совпадает, со свойством ViewModel

2024-10-02 07:52 UTC, dosymep commented on src/RevitValueModifier/Models/RevitRepository.cs
> +        internal List<ElementId> GetCategoryIds(List<RevitElement> revitElements) => revitElements
в этом методе нужно удалить дубликаты категорий `Distinct`

2024-10-02 07:52 UTC, dosymep commented on src/RevitValueModifier/Models/RevitParameter.cs
> +                ParamTypeName = _localizationService.GetLocalizedString("MainWindow.SystemParameter");
попробуй давать имена через конвертер, тогда сервис локализации будет в окне

2024-10-02 07:52 UTC, dosymep commented on src/RevitValueModifier/Models/RevitElement.cs
> +                TaskDialog.Show(
лучше выброси корректное исключение

2024-10-02 07:52 UTC, dosymep commented on src/RevitValueModifier/Models/RevitElement.cs
> +                TaskDialog.Show(
лучше выброси исключение

2024-10-02 07:52 UTC, dosymep commented on src/RevitValueModifier/Models/RevitElement.cs
> +            ParamValue = paramValueMask;
мы же договаривались, что будет обычный string.Replace

2024-10-02 07:52 UTC, dosymep commented on src/RevitValueModifier/ViewModels/MainViewModel.cs
> +        public List<RevitElement> RevitElements {
Для отображения ревит элементов, у тебя должна быть своя ViewModel

2024-10-02 07:52 UTC, dosymep commented on src/RevitValueModifier/Models/RevitElement.cs
> +        public event PropertyChangedEventHandler PropertyChanged;
Убери реализаци уведомлений об изменении, сделай через ViewModel

2024-10-02 07:52 UTC, dosymep commented on src/RevitValueModifier/Models/RevitElement.cs
> +            var elemType = Elem.GetElementType();
перенеси `elemType` ближе к его использованию

2024-10-02 07:52 UTC, dosymep commented on src/RevitValueModifier/Models/RevitElement.cs
> +                return string.Empty;
верни null

2024-10-02 07:52 UTC, dosymep commented on src/RevitValueModifier/Models/RevitElement.cs
> +            switch(parameter.StorageType) {
надо уточнить, как метод конвертации параметров должен работать
- должен ли он писать с единицей измерений
- должен ли он писать без единицы измерения
- не понятно с какой локалью
- конвертация всегда в строку и для строковых параметров?

2024-10-02 09:02 UTC, DivinN commented on .nuke/parameters.RevitValueModifier.json
Перенесу на BIM

2024-10-02 11:51 UTC, DivinN commented on src/RevitValueModifier/Models/RevitElement.cs
> +            ParamValue = paramValueMask;
очень хотелось так с:

2024-10-02 13:21 UTC, DivinN commented on src/RevitValueModifier/Models/RevitElement.cs
> +                return string.Empty;
оставил как было, т.к. так удобнее заменять в строке значения 
(строка 97) ParamValue = regexForParam.Replace(ParamValue, val, 1);

2024-10-03 12:07 UTC, DivinN commented on src/RevitValueModifier/Models/RevitParameter.cs
> +                ParamTypeName = _localizationService.GetLocalizedString("MainWindow.SystemParameter");
Реализовал как в примере https://stackoverflow.com/questions/58493209/ivalueconverter-and-binding-a-dependencyobject

2024-10-04 05:46 UTC, dosymep requested changes

2024-10-04 05:46 UTC, dosymep commented on src/RevitValueModifier/Models/RevitRepository.cs
> +                .Select(e => new RevitElementViewModel(e, _localizationService))
в репозитории не должно быть созданий и ссылка на ViewModel

2024-10-04 05:46 UTC, dosymep commented on src/RevitValueModifier/Views/ParamTypeConverter.cs
> +        protected override Freezable CreateInstanceCore() {
круто, молодец :)

2024-10-04 14:43 UTC, DivinN commented on src/RevitValueModifier/Views/ParamTypeConverter.cs
> +        protected override Freezable CreateInstanceCore() {
с:

2024-10-07 08:44 UTC, dosymep submitted a review, later dismissed

2024-10-07 09:49 UTC, dosymep approved these changes

2024-10-07 09:49 UTC, merged