RevitSheduleImport: Создан плагин "Импорт Excel"
Bim4Everyone/RevitPlugins pull request #91
Opened 2024-10-08 09:19 UTC by vlastroG

# Импорт Excel

## Описание

Плагин позволяет импортировать листы из Excel в Revit в виде спецификаций.

Импортированная спецификация представляет собой "фиктивную спецификацию" - спецификацию на неиспользуемую категорию элементов. Все данные из листа Excel попадают в заголовок спецификации Revit, также применяется форматирование.

### Поддерживаемое форматирование:

- Шрифт текста
- Размер текста
- Выравнивание текста по горизонтали/вертикали
- Цвет текста (который задан через RGB, но не через % от оттенка)
- Стиль текста: жирный/курсив/подчеркнутый
- Скрытие границ ячеек
- Цвет фона ячейки (который задан через RGB, но не через % от оттенка)
- Размер ячеек (конвертируется из единиц Excel в мм)

Пример импорта:

![image](https://github.com/user-attachments/assets/27f57455-fbc8-40ef-b016-30051cf85c86)
Слева Revit, справа Excel.

### Особенности импорта:

Если цвет задан процентом от оттенка, будет импортирован 100% оттенок.
![image](https://github.com/user-attachments/assets/dfb80a9e-8b20-4ee6-be10-b999129eec4d)

Если в Excel текст может выходить за границы ячейки, то в спецификации Revit так не происходит. Поэтому такие ячейки надо объединять в Excel:
![image](https://github.com/user-attachments/assets/4420469c-deb3-4d5d-b966-4ead7e6c42fa)
![image](https://github.com/user-attachments/assets/9aaf12cc-8ca2-4c38-b043-807479393409)

2024-10-09 06:42 UTC, dosymep requested changes

2024-10-09 06:42 UTC, dosymep commented on src/RevitScheduleImport/Services/LengthConverter.cs
> +        /// <returns>Размер в внутренних единицах Revit (футах)</returns>
во внутренних

2024-10-09 06:42 UTC, dosymep commented on src/RevitScheduleImport/Services/LengthConverter.cs
> +            // fucking width
будь немного корректнее

2024-10-09 06:42 UTC, dosymep commented on src/RevitScheduleImport/Services/LengthConverter.cs
> +        /// <param name="excelColumnWidth">Высота строки в единицах Excel</param>
параметр в документации не совпадает с параметром в методе

2024-10-09 06:42 UTC, dosymep commented on src/RevitScheduleImport/Services/ScheduleImporter.cs
> +            var defaultFontSize = columns.Style.Font.FontSize;
не используемая переменная

2024-10-09 06:42 UTC, dosymep commented on src/RevitScheduleImport/Services/ScheduleImporter.cs
> +                var leftTopCell = mergedRange.FirstCell().Address;
в таких случаях лучше используй имя типа, вместо `var`

2024-10-09 06:42 UTC, dosymep commented on src/RevitScheduleImport/Services/ScheduleImporter.cs
> +            var border = cell.Style.Border;
не используемая переменная

2024-10-09 06:42 UTC, dosymep commented on src/RevitScheduleImport/Services/ScheduleImporter.cs
> +                // fucking excel
ну ты понял :)

2024-10-09 06:42 UTC, dosymep commented on src/RevitScheduleImport/Services/ScheduleImporter.cs
> +                    return cellValue.GetDateTime().ToString();
добавь либо русскую, либо текущую локаль явно

2024-10-09 06:42 UTC, dosymep commented on src/RevitScheduleImport/ViewModels/CategoryViewModel.cs
> +        public string Name => _category?.Name ?? string.Empty;
категория не может быть `null`

2024-10-09 06:42 UTC, dosymep commented on src/RevitScheduleImport/Views/MainWindow.xaml
> +                Width="200"
отсортируй свойства

2024-10-09 06:42 UTC, dosymep commented on src/RevitScheduleImport/RevitScheduleImportCommand.cs
> +            PluginName = "RevitScheduleImport";
Впиши имя плагина

2024-10-09 06:42 UTC, dosymep commented on src/RevitScheduleImport/RevitScheduleImportCommand.cs
> +                var localizationServise = kernel.Get<ILocalizationService>();
опечатка

2024-10-09 07:06 UTC, vlastroG commented on src/RevitScheduleImport/Services/LengthConverter.cs
> +        /// <returns>Размер в внутренних единицах Revit (футах)</returns>
исправил

2024-10-09 07:06 UTC, vlastroG commented on src/RevitScheduleImport/Services/LengthConverter.cs
> +            // fucking width
написал развернуто

2024-10-09 07:06 UTC, vlastroG commented on src/RevitScheduleImport/Services/LengthConverter.cs
> +        /// <param name="excelColumnWidth">Высота строки в единицах Excel</param>
исправил

2024-10-09 07:28 UTC, vlastroG commented on src/RevitScheduleImport/RevitScheduleImportCommand.cs
> +                var localizationServise = kernel.Get<ILocalizationService>();
исправил

2024-10-09 07:28 UTC, vlastroG commented on src/RevitScheduleImport/RevitScheduleImportCommand.cs
> +            PluginName = "RevitScheduleImport";
сделал

2024-10-09 07:28 UTC, vlastroG commented on src/RevitScheduleImport/Views/MainWindow.xaml
> +                Width="200"
отсортировал

2024-10-09 07:32 UTC, vlastroG commented on src/RevitScheduleImport/Services/ScheduleImporter.cs
> +                    return cellValue.GetDateTime().ToString();
прописал текущую локаль

2024-10-09 07:32 UTC, vlastroG commented on src/RevitScheduleImport/Services/ScheduleImporter.cs
> +                var leftTopCell = mergedRange.FirstCell().Address;
сделал

2024-10-09 07:32 UTC, vlastroG commented on src/RevitScheduleImport/Services/ScheduleImporter.cs
> +            var border = cell.Style.Border;
убрал

2024-10-10 05:42 UTC, dosymep approved these changes

2024-10-10 06:16 UTC, merged